(Operators-Operators)=
# Operators

(Operators-Definitions)=
## Definitions

(Operators-Operators--Derived-Functions)=
### Operators & Derived Functions

We have already seen some operators: _reduce_ (described in {numref}`Some-Primitive-Functions-Reduce`), _axis_ (described in {numref}`Some-Primitive-Functions-Axis-Specification`), and _each_ (described in {numref}`Nested-Arrays-Continued-Each`.
Let us define precisely what they are:

 - there are built-in (_primitive_) operators and user-defined operators;
 - an _operator_ is similar to a function, but rather than working on arrays to produce a result which is also an array, an operator works on functions (and sometimes, arrays) to produce a new function;
 - the new function generated by the operator and its argument(s) is called a _derived function_. The derived function can be applied to arrays in the same way as any other function;
 - the arguments passed to the operator are often referred to as _operands_, to distinguish them from the arguments to the derived function;
 - monadic operators take a single operand on their **left**. This is in contrast to monadic functions, which take their argument on the right;
 - dyadic operators have two operands, one on each side. The operands to an operator are usually functions, but it is not uncommon for user-defined operators to take on function and one array operand;
 - the derived function, in turn, can be monadic, dyadic, or ambivalent; and
 - neither of the functions supplied as arguments to an operator, nor the resultant derived function, can be niladic.

For example, in the expression below, the operator _reduce_ (`/`) _operates on_ the function _plus_ to produce the derived function _plus reduce_.
This derived function is then applied to `3 5 6` to produce the result `14`:

In [1]:
+/3 5 6

```{admonition} Beware 
:class: warning
You must not be confused by the fact that some symbols are used to represent both a function and an operator, such as `/` and `\`, for example.
```

Let us compare two expressions:

 1. using `/` as the function _compress_, which takes two array arguments:

In [2]:
1 1 0 1 0 / 6 2 9 4 5

 2. using `/` as the operator _reduce_, which takes a function as a left operand:

In [3]:
+/ 6 2 9 4 5

The association of `+` with `/` creates a _derived function_ which could be parenthesised as `(+/)`, even though it is not necessary to do so.

For clarification, we can define a synonym for the derived function:

In [4]:
Sum ← +/

Until now, we have only considered `+/` (or `Sum`) as a monadic derived function:

In [5]:
Sum 6 2 9 4 5

But we shall soon see that it may also be used as a dyadic function:

In [6]:
2 Sum 6 2 9 4 5

So, we can say that this _derived function_ is _ambivalent_.

(Operators-Sequences-of-Operators)=
### Sequences of Operators

_Derived functions_ behave exactly like plain primitive functions.
So, they can be the argument of a second (and a third, ...) operator:

In [7]:
+/¨ (3 4 6)(4 9 7 1)(3 1)

The left argument of the operator _each_ `¨` is the derived function `+/`, so we could have written:

In [8]:
Sum¨ (3 4 6)(4 9 7 1)(3 1)

Now, suppose that we no longer want to add up vectors, but three small matrices instead:

In [9]:
⎕← A ← 2 3⍴⍳6

In [10]:
⎕← B ← 4 2⍴1 0 0 1 0 1 1 0

In [11]:
⎕← C ← 3 5⍴8 3 4 2 0 0 3 5 1 7 3 6 2 1 7

Because they are matrices, we must specify the axis along which we add them up.
Of course, we could use the two symbols `/` and `⌿`, but if the arrays had been of a higher rank, an explicit axis specification might have been necessary.
It could also be that we just prefer to use the explicit axis specification.
If so, a third level of operator⁽*⁾ can be added:

```{admonition} Footnote 
:class: note
Although the _axis specification_ shares some properties with operators, it is a special syntactical element and not really an operator. See {numref}`Operators-Axis` for more information.
```

In [12]:
+/[2]¨A B C

In [13]:
+/[1]¨A B C

When in doubt regarding what is the function operand to which operator, try parenthesising everything successively, to make it clearer what derived functions come from where.

In the two examples above, the first operator is `/`, then the second "operator" is `[]`, and the third operator is `¨`:

In [14]:
(((+/)[2])¨)A B C

(Operators-List-of-Built-in-Operators)=
### List of Built-in Operators

Dyalog APL has a rich set of built-in operators.
You will find a full list with detailed syntax and examples in {numref}`Appendices-Dyalog-APL-Operators`.

(Operators-More-About-Some-Operators-You-Already-Know)=
## More About Some Operators You Already Know

(Operators-Reduce)=
### Reduce

Up to now, we have used the operator _reduce_ with rather basic functions (`+`, `×`, `⌈`, `∧`), but it can also be used, less obviously, with functions like _reshape_, _compress_, and _replicate_.
In these cases, the derived function typically takes a 2-item nested vector as its argument, and the effect is to insert the function (the operand to the operator) between the two items of this vector.

Just remember that, since `+/ (2 4 3)(7 1 5)` is equivalent to `⊂(2 4 3) + (7 1 5)`, then `⍴/ (2 4 3)(7 1 5)` is also equivalent to `⊂(2 4 3) ⍴ (7 1 5)`.

Here is an example of a _reduction by reshape_:

In [15]:
⍴/(2 5)(3 1 9 4 1 0 7)

This _looks_ very similar to

In [16]:
2 5⍴3 1 9 4 1 0 7

But we can see the results are different.
The result of the _reduction by reshape_ is not a matrix, but a scalar containing a _nested_ matrix, for the reason already seen in {numref}`Nested-Arrays-Continued-Reduction`: the reduction of a vector always gives a scalar.

Now, here is a _reduction by compression_, another by _replication_, and one by _index of_:

In [17]:
//(1 1 0 1 0 1 1)'Strange'

In [18]:
//(1 1 0 4 0 1 2)'Strange'

In [19]:
⍳/(2 6 1 7)(2 4⍴3 7 8 4 2 5 6 0)

(Operators-n-Wise-Reduce)=
### n-Wise Reduce

(Operators-Elementary-Definition)=
#### Elementary Definition

The derived functions of _reduce_ can be used with two arguments.
When the second argument is present, the form is called _n-wise reduce_.

When applied to vectors, _n-wise reduce_ has the syntax `r ← n F/ vector`, where `F` denotes a dyadic function.

This special kind of _reduce_ splits the vector into overlapping slices of length equal to `n`, reduces each slice using the specified function `F`, and then catenates the results together.

So, for example, `2 ×/ 8 10 7 2 6 11` starts by creating overlapping slices of length `2`:

In [20]:
(8 10)(10 7)(7 2)(2 6)(6 11)

Then, we apply the reduction `×/` on each slice and catenate everything:

In [21]:
(×/8 10),(×/10 7),(×/7 2),(×/2 6),(×/6 11)

You can verify that this is, indeed, the result we get:

In [22]:
2 ×/ 8 10 7 2 6 11

As another example, we can explain the result of

In [23]:
3 +/ 8 10 7 2 6 11

because we create overlapping slices of length `3`, apply _plus-reduce_ on each slice, and then catenate everything together:

In [24]:
(+/8 10 7),(+/10 7 2),(+/7 2 6),(+/2 6 11)

The length of the result vector is `(1+≢vector)-n`.

In the two examples above, we did not really need to do the catenation explicitly, because the results of applying `×/` and `+/` on each slice were simple scalars.
However, if we try an example where the reduction gives a nested result, we will see that we _do_ need to catenate everything together.

Here is an example of an _n-wise catenate reduction_:

In [25]:
2 ,/ 8 10 7 2 6 11

If we create the overlapping slices by hand and do not catenate the results together, we get a result that is nested too deep:

In [26]:
(,/8 10)(,/10 7)(,/7 2)(,/2 6)(,/6 11)

Thus, we do have to catenate the results after applying the reduction to each slice:

In [27]:
(,/8 10),(,/10 7),(,/7 2),(,/2 6),(,/6 11)

(Operators-Full-Definition)=
#### Full Definition

The general syntax is `r ← n F/[axis] array`, where `F` stands for any dyadic function.

 - the `array` is split into slices along the specified `axis`;
 - the left argument `n` can be positive (as in the examples above), zero, or negative;
 - if `n` is positive, _reduce_ is applied to slices of length equal to `n`;
 - if `n` is zero, the result is an array with the same shape as _array_, except that its length along the axis selected by `axis` is incremented by 1 and filled with the _identity item_ for the function `F`. This is explained in {numref}`Operators-application-to-n-wise-reduction`; and
 - if `n` is negative, each slice is reversed before _reduce_ is applied.

Here are some examples which use the matrix below:

In [28]:
tam ← 3 5⍴2 3 5 8 8 4 6 2 5 9 1 4 9 7 8

Find the largest items of 2 adjacent columns:

In [29]:
2 ⌈/ tam

Add up pairs of adjacent rows:

In [30]:
2 +⌿ tam

Return a matrix with one more column, filled with zeroes (identity item of addition):

In [31]:
0 +/ tam

Return a matrix with one more row, filled with ones (identity item of multiplication):

In [32]:
0 ×/[1] tam

Obtain the differences between adjacent values `(14-11)(15-14)...`:

In [33]:
¯2 -/ 11 14 15 21 23 30 28 34

(Operators-Axis)=
### Axis

Strictly speaking, _axis_ is not an operator.
It has different syntax (consisting of two brackets enclosing a numeric value to the right of a function) and applies in different ways depending on the function that it modifies (its operand).
However, applying a function "with _axis_" does apply a transformation and produces a derived function, and it is common to think of _axis_ as an operator.

It is possible to use _axis_ with any of the scalar dyadic functions.
This can be useful, for example, to add the items of a vector to each of the rows of a matrix, or multiply the columns of a matrix by different values:

In [34]:
tam

In [35]:
tam +[1] 8 6 9

In [36]:
tam ×[2] 2 5 0 2 1

The list of all scalar dyadic functions is given in {numref}`Appendices-Scalar-Functions`.

The following functions can also use _axis_:

| Monadic Function | Description |
| :- | :- |
| `↑` and `↓` | _mix_ and _split_ |
| `⌽` `⊖` | _reverse_ |
| `,` | _ravel with axis_ |
| `⊂` | _enclose with axis_, _partitioned enclose_ |
| `⊂` and `⊃` | if `⎕ML>1`, APL2-like _split_ and _mix_, c.f. {numref}`Nested-Arrays-Continued-Compatibility-and-Migration-Level` |

| Dyadic Function | Description |
| :- | :- |
| `+` `×` `⌈` `∧` `≤` etc... | all scalar dyadic functions |
| `↑` and `↓` | _take_ and _drop_ |
| `/` and `⌿` | _compress_ and _replicate_ |
| `\` and `⍀` | _expand_ and _scan_ (see next section) |
| `⌽` `⊖` | _rotate_ |
| `,` `⍪` | _catenate_ |
| `,` `⍪` | _laminate_ |
| `⊂` | _partitioned enclose_ |

(Operators-Scan)=
## Scan

_Scan_ is represented by the symbol `\` or `⍀`.
Its most general syntax is `r ← F\[axis] array`, where `F` stands for any appropriate dyadic function.

To understand how it works, let us apply it to a vector.

The nth item of `F\vector` is equal to `F/n↑vector`. A worked example follows:

In [37]:
+\ 3 6 1 8 5

 1. the 1st item is equal to `+/3`, which is `3`;
 2. the 2nd item is equal to `+/3 6`, which is `9`;
 3. the 3rd item is equal to `+/3 6 1`, which is `10`;
 4. the 4th item is equal to `+/3 6 1 8`, which is `18`; and
 5. the 5th item is equal to `+/3 6 1 8 5`, which is `23`.

Try to use a reasoning similar to the one above to understand the result of the _times scan_ shown below:

In [38]:
×\ 3 6 1 8 5

Warning!
It would be a mistake to always try to deduce the value of each item in the result from its immediate left neighbour.
While it is possible to do this for commutative functions like addition and multiplication, it is not appropriate for non-commutative functions like subtraction.

In fact, the result of `-\ 3 6 1 8 5` is **not** `3 ¯3 ¯4 ¯12 ¯17`, but something else entirely:

In [39]:
-\ 3 6 1 8 5

 1. the 1st item is equal to `-/3`, which is `3`;
 2. the 2nd item is equal to `-/3 6`, which is `¯3`;
 3. the 3rd item is equal to `-/3 6 1`, which is `¯2`, the result of `3-6-1` and **not** `(3-6)-1`;
 4. the 4th item is equal to `-/3 6 1 8`, which is `¯10`; and
 5. the 5th item is equal to `-/3 6 1 8 5`, which is `¯5`.

So, be careful when using _scan_ with non-commutative functions.

When applied to matrices or higher-rank arrays, _scan_ works along the specified axis.
If the axis specification is omitted, `\` works along the _last_ axis and `⍀` works along the _first_ axis.

In [40]:
+\[2]tam  ⍝ same as +\tam

In [41]:
+\[1]tam  ⍝ same as +⍀tam

(Operators-Scan-with-Binary-Values)=
### Scan with Binary Values

_Scan_ is very useful when applied to binary values.

In [42]:
∨\ 0 0 0 0 1 1 0 1 0 0 1 1

Because the function _or_ gives the result `1` as soon as one of its arguments is `1`, _or-scan_ repeats the first `1` up to the end of the vector.
In a way, you can see `∨\` as a knife spreading butter from left to right, and the `1` is the butter.

Other interesting patterns can be obtained by changing the function used.
For example, you can get the effect of "a knife spreading butter", where the `0` is the butter, if you use `∧\` instead of `∨\`:

In [43]:
∧\ 1 1 1 1 0 1 1 0 0 1 1 0

In the example above, as soon as _and-scan_ finds a `0`, everything else turns into a `0`.

The _less-than-scan_ marks the position of the first `1` and the _less-than-or-equal-scan_ marks the position of the first `0`:

In [44]:
<\ 0 0 0 0 1 1 0 1 0 0 1 1

In [45]:
≤\ 1 1 1 1 0 1 1 0 0 1 1 0

(Operators-Applications)=
### Applications

_Scan_ can be used to solve common problems in a very simple way:

(Operators-Inflate-Values)=
#### Inflate Values

Someone forecasts investments in a foreign country for the next five years:

In [46]:
inv ← 2000 5000 6000 4000 2000

But the country in question suffers from inflation, and the inflation rates are forecasted as follows:

In [47]:
inf ← 2.6 2.9 3.4 3.1 2.7

The cumulative sequence of these inflation rates can be calculated by multiplying them all with a _multiply-scan_:

In [48]:
7 3⍕ ×\ 1+inf÷100

Now, the investments expressed in "future values" would be:

In [49]:
9 2⍕ inv × ×\1+inf÷100

Finally, the year after year cumulative investment may be obtained by a _plus-scan_:

In [50]:
9 2⍕ +\ inv × ×\1+inf÷100

As you can see, we employed two _scans_ in the same expression.

(Operators-Remove-LeadingTrailing-Blanks)=
#### Remove Leading/Trailing Blanks

One often has to remove leading (or trailing) blanks from a character vector.
We can use the _or-scan_ to do it.
The details of the method are shown here:

In [51]:
lb ← '    Remove my 4 leading blanks.'
lb≠' '

In [52]:
∨\ lb≠' '

In [53]:
(∨\ lb≠' ')/lb

This can be coded into a small utility function:

In [54]:
CutBlanks ← {(∨\' '≠⍵)/⍵}

This expression is recognised by Dyalog APL as an _idiom_ and is thus very fast.

To remove trailing blanks, it would suffice to reverse the vector, remove leading blanks as above, and then reverse it back again.

(Operators-Outer-Product)=
## Outer Product

Imagine that you have calculated the multiplication table for the integers 1 to 9; you could present it like this:

$$\begin{array}{|c|rrrrrrrrr|}
\hline
\color{red}\times & 1 & 2 & 3 & 4 & 5 & 6 & \color{red} 7 & 8 & 9 \\
\hline
1 & 1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9 \\
2 & 2 & 4 & 6 & 8 & 10 & 12 & 14 & 16 & 18 \\
\color{red} 3 & 3 & 6 & 9 & 12 & 15 & 18 & \color{red} {21} & 24 & 27 \\
4 & 4 & 8 & 12 & 16 & 20 & 24 & 28 & 32 & 36 \\
\text{etc.} & \text{etc.} & & & & & & & & & & \\
9 & 9 & 18 & 27 & 36 & 45 & 54 & 63 & 72 & 81 \\
\hline
\end{array}$$

The task of calculating this table consists of taking pairs of items of two vectors (the column and row headings) and combining them with the function at the top left.
For example, `3` times `7` gives `21` (highlighted in red above).
Once the operation has been repeated for all the possible pairs, one obtains what is called, in APL, the _outer product_.

We can change the values and replace the multiplications with additions:

$$\begin{array}{|c|rrrrrr|}
\hline
\color{red}+ & 8 & 5 & 15 & \color{red} 9 & 11 & 40\\
\hline
5 & 13 & 10 & 20 & 14 & 16 & 45 \\
\color{red} 4 & 12 & 9 & 19 & \color{red} 13 & 15 & 44 \\
10 & 18 & 15 & 25 & 19 & 22 & 50 \\
3 & 11 & 8 & 18 & 12 & 14 & 43 \\
\hline
\end{array}$$

The _outer product_ operator looks like `∘.F`, where `F` is an appropriate dyadic function.
The symbol `∘` is a _jot_ and you can type it with <kbd>APL</kbd>+<kbd>j</kbd>.

For example, for the multiplication table you can use `∘.×`:

In [55]:
(⍳9) ∘.× ⍳9

And for the addition table above, you can use `∘.+`:

In [56]:
5 4 10 3 ∘.+ 8 5 15 9 11 40

As you can see, the _outer product_ is also slightly special, in that the operand function `F` goes on the right of `∘.`, and not on the left.

Also, notice that the left column of the table is the left argument vector to the function derived from the _outer product_ and the top row is the right argument vector.
In fact, in the expression `r ← left ∘.F right`, the shape of the result `r` is `(⍴r) ≡ (⍴left),⍴right`.

(Operators-Extensions)=
### Extensions

(Operators-Other-Functions)=
#### Other Functions

The function used in an _outer product_ can be any primitive or user-defined dyadic function, so _outer product_ is an operator of amazing power.

Imagine you have written a little function to calculate the length of the hypotenuse of a right-angled triangle from the lengths of the other 2 sides given as the left and right argument:

In [57]:
Hypo ← {((⍺*2)+(⍵*2))*0.5}
3 Hypo 4

You can test it on a number of combinations of lengths in one expression like this:

In [58]:
8 3⍕ 3 6 12 ∘.Hypo 4 1 8 7 5

Now, let us have some fun with relational functions:

In [59]:
(⍳5) ∘.= (⍳5)

In [60]:
(⍳5) ∘.< (⍳5)

In [61]:
(⍳5) ∘.≥ (⍳5)

We shall study some applications of _outer product_ like `∘.<` or `∘.⌊` in {numref}`Operators-Applications-of-Outer-Product`.

Whenever the function `F` does not produce a scalar, the _outer product_ `∘.F` produces a nested array. This is the case with _outer products_ like `∘.⍴`, `∘.,`, or `∘./`:

In [62]:
3 4 2 ∘.⍴ 6 3 7

In [63]:
3 0 2 ∘./ 5 1 7

In [64]:
3 1 2 ∘., 6 3 0 7

In [65]:
3 2 4 ∘.↑ 5 8 4

(Operators-Other-Shapes-and-Types-of-Data)=
#### Other Shapes and Types of Data

So far, we have applied _outer product_ to numeric vectors; it can, of course, also be used with character data and higher-rank arrays.
When applied to higher rank arrays, the result becomes very big quickly, because each item of the left array has to be combined with each item of the right one.

Remember, in the expression `r ← left ∘.F right`, the shape of `r` is equal to `(⍴left),(⍴right)`.

In [66]:
⎕← left ← ↑'DIMITRI' 'GUNTHER'

In [67]:
right ← 'VERONICA'

Now, we wish to study the result of `left ∘.= right`.
To help you visualise the comparisons being made, we catenate the left argument matrix on the left of the result and catenate the right argument vector on top:

In [68]:
(2 9⍴' ',right)⍪[2]left,left ∘.= right

The left argument is a matrix with shape `2 7` and the right argument is a vector with shape `8`, so the result is a 3D array with shape `2 7 8`.
Each of the two major cells corresponds to comparing one of the names in the left argument to the name `'VERONICA'`.

(Operators-Applications-of-Outer-Product)=
### Applications of Outer Product

(Operators-Exhaustive-Search)=
#### Exhaustive Search

Because _outer product_ uses a dyadic function to combine **all** items of the left argument with **all** items of the right argument, _outer product_ is often used when some kind of exhaustive computation needs to be done.
One such example is that of exhaustive search.

As an example, suppose you want to figure out if there is a way to add one number from the vector `5 1 16 42 63 7 10` to another number from the vector `24 45 18 31 29 43 67` to get `73`.

With _outer product_, this is quite an easy question to answer:

In [69]:
5 1 16 42 63 7 10∘.+24 45 18 31 29 43 67

In [70]:
73∊5 1 16 42 63 7 10∘.+24 45 18 31 29 43 67

If you flip the arguments to _membership_ and use _where_, you can find the position(s) where `73` is:

In [71]:
⍸(5 1 16 42 63 7 10∘.+24 45 18 31 29 43 67)∊73

This pattern of exhaustive computations is fairly common, and although it generally is not the most computationally efficient way of solving a problem, it is generally fast enough to prototype as a first approach.

(Operators-Draw-a-Bar-Chart)=
#### Draw a Bar Chart

Imagine that you have to represent a list of values with a bar chart.
Perhaps you will use dedicated graphical software, and you'd be right, but just have a look at this elegant solution, which again uses an _outer product_.

Here is the list of values that we want to chart:

In [72]:
nums ← 1 3 0 7 9 8 5 4 2 3 1

Let us first calculate the vertical scale.
It is made of the integers from 9 to 1 in reverse order and can be obtained by:

In [73]:
⌽⍳⌈/nums

Then, let us compare this scale to the values; an _outer product_ will build columns of `1`s up to the correct height:

In [74]:
(⌽⍳⌈/nums) ∘.≤ nums

Finally, to draw the graph, we can index a two-character vector, exactly as we did in {numref}`Data-and-Variables-The-Shape-of-the-Result`:

In [75]:
' ⎕'[1+(⌽⍳⌈/nums)∘.≤nums]

(Operators-Decreasing-Refunding)=
#### Decreasing Refunding

Some students have spent money to buy expensive books for their studies:

In [76]:
exp ← 740 310 1240 620 800 460 1060

Their university agrees to refund them, but places the following limits on the refunding rates:

| Expense range | Refund rate |
| :- | :- |
| 0 - 500 | 80% |
| 500 - 900 | 50% |
| 900+ | 0% |

We could say exactly the same thing in a somewhat different way:

Expenses from 0 to 900 have a refund rate of 50% and expenses up to 500 get an **additional** 30%.

Even if this rule may seem strange, both methods give the same result.
For example, a student who spent 740€ would get:

 - using the initial table, 80% of 500 plus 50% of 240:

In [77]:
(0.8×500)+0.5×240

 - using the reworded rule, 50% of 740 plus 30% of 500:

In [78]:
(0.5×740)+0.3×500

Now, let us limit the expenses to the given maxima:

In [79]:
exp ∘.⌊ 900 500

The first column of the result above contains the expenses capped at 900 (which get a refund of 50%) and the second column contains the expenses capped at 500 (which get an additional 30%).

So, according to our modified rule, we must pay 50% of the first column plus 30% of the second, which we can do by multiplying the columns with `0.5 0.3` (using an _axis_ operator) and then adding them:

In [80]:
+/ (exp∘.⌊900 500) ×[2] 0.5 0.3

And the total refund is, of course:

In [81]:
+/ +/(exp∘.⌊900 500)×[2]0.5 0.3

If we laminate the original vector, we can see the expenses and the refunding:

In [82]:
exp,[.5] +/(exp∘.⌊900 500)×[2]0.5 0.3

(fig-Outer_Product)=
```{figure} ../res/Outer_Product.png
---
name: Outer_Product
---
"APLer applying sunscreen outside."
```

(Operators-Outer-Product-Exercise)=
### Outer Product Exercise

````{exercise}
:label: ex-complex-refunding
Let us try to generalise the method used above to compute refunds.

In our example, we had chosen a very simple case, because we had only two slices, and all students used the same scale.
Let us now imagine a slightly more complex case:

 - the students are classified in three categories, which have different refunding rates; and
 - we now have four different expense ranges.

The new conditions are expressed with the traditional notation in the table below:

| Category \ Range | 0 to 600 | 600 to 1.100 | 1.100 to 1.500 | 1.500 to 2.000 |
| :- | :- | :- | :- | :- |
| Category 1 | 100% | 100% | 80% | 50% |
| Category 2 | 100% |  70% | 30% | 10% |
| Category 3 |  80% |  60% | 20% |  5% |

```APL
limits ← 600 1100 1500 2000
rates ← 3 4⍴100 100 80 50 100 70 30 10 80 60 20 5
```

Define a function `Refund` to solve this problem.
The function should take the limits vector, the rates matrix, the expenses vector, and the categories vector, as right arguments.
The return value should be a vector with the refunded amount to each student.

Using loops is strictly prohibited and may be punished with high severity!

Make use of the variables `expenses` and `categories` defined below and verify your solution by comparing it to the values shown below.
````

In [83]:
⎕RL ← 73
expenses ← ?350⍴2500
categories ← ?350⍴3
⎕← 2 10↑categories,[.5]expenses

In [84]:
10↑Refund limits rates categories expenses

VALUE ERROR: Undefined name: rates
      10↑Refund limits rates categories expenses
                       ∧

In [85]:
+/Refund limits rates categories expenses

VALUE ERROR: Undefined name: rates
      +/Refund limits rates categories expenses
                      ∧

(Operators-Inner-Product)=
## Inner Product

_Inner product_ is a generalisation of what mathematicians call _matrix product_, a tool considered by most students as extremely abstract, full of bizarre notations, like $\sum a_{ij}b_{jk}$, and obviously far removed from everyday problems.
You will discover that:

 - the concept is really simple, nearly obvious; and
 - it can be applied to many real life problems.

A simple example will help us.

(Operators-A-Concrete-Situation)=
### A Concrete Situation

A company intends to open a series of hotels and resorts in four countries.
This requires serious investments over a period of five years.
The following table shows these investments (in millions of dollars, of course!):

| Country vs Year | Year 1 | Year 2 | Year 3 | Year 4 | Year 5|
| :- | -: | -: | -: | -: | -: |
| Greece | 120 | 100 | 40 | 20 | 0 |
| Brazil | 200 | 150 | 100 | 120 | 200 |
| Egypt | 50 | 120 | 220 | 350 | 600 |
| Argentina | 0 | 80 | 100 | 110 | 120 |

These figures are contained in a matrix called `invest`:

In [86]:
invest ← 120 100 40 20 0 200 150 100 120 200 50 120
⎕← invest ← 4 5⍴invest,220 350 600 0 80 100 110 120

These investments will be supported by the company itself plus two banks, each taking a certain percentage of the total, depending on the evaluation of each project.
The following table shows how the risks are shared:

| Entity vs Country | Greece | Brazil | Egypt | Argentina |
| :- | -: | -: | -: | -: |
| Bank 1 | 50 | 10 | 20 | 30 |
| Bank 2 | 20 | 60 | 40 | 30 |
| Company | 30 | 30 | 40 | 40 |

Those percentages are contained in a matrix named `percent`:

In [87]:
⎕← percent ← 3 4⍴50 10 20 30 20 60 40 30 30 30 40 40

We would like to calculate, year by year, how much each of the 3 partners is engaged in this project.
For example, let us try to evaluate the contribution of Bank 2 during Year 3:

| Country | Project valuation | Stake | Total invested |
| :- | -: | -: | -: |
| Greece | 40 | 20% | 8 |
| Brazil | 100 | 60% | 60 |
| Egypt | 220 | 40% | 88 |
| Argentina | 100 | 30% | 30 |

The total invested is, thus, 186.

This could have been obtained by the sum of four products:

In [88]:
+/ percent[2;] × invest[;3]÷100

In order to calculate the total invested for each partner and each year, we should repeat that algorithm for all the rows of `percent`, and all the columns of `invest`: this is precisely what an _inner product_ does.

And because it _adds_ a series of _products_, it will be expresseed by a dot (the operator) between a plus and a multiply sign, like this:

In [89]:
percent +.× invest÷100

In {numref}`fig-Inner_Product`, we have detailed the elementary products which lead to the calculation for bank 2 in year 3:

(fig-Inner_Product)=
```{figure} ../res/Inner_Product.png
---
name: Inner_Product
---
Diagram representing the _inner product_ operation.
```

{numref}`fig-Inner_Product` has a great advantage: it clearly shows the relations that exist between the 3 matrices:

 - the left argument has as many columns as the right one has rows; and
 - the result has as many rows as the left argument and as many columns as the right one.

As you can see, the item `result[x;y]` is calculated from row `x` of the left argument (`⍺[x;]` in dfn notation) and column `y` of the right argument (`⍵[;y]` in dfn notation).

These rules will be generalised in the next section.

(Operators-Definition-of-Inner-Product)=
### Definition of Inner Product

The syntax of _inner product_ is `r ← x f.g y`, where the _inner product_ is represented by a dot (`.`) and `f` and `g` represent two appropriate dyadic functions (either primitive or user-defined).

The arguments may be arrays of any rank: scalars, vectors, matrices, or higher-rank arrays.
The shape of the arguments and the shape of the result follow very simple rules:

 - the length of the last dimension of the left argument must be equal to the length of the first dimension of the right argument (in other words, `(¯1↑⍴x)≡1↑⍴y`); and
 - the shape of the result is the catenation of the argugments' shapes, in which the common dimension has disappeared (in other words, `(⍴r)≡(¯1↓⍴x),1↓⍴y`).

Of course, as usual, scalars are repeated to fit the appropriate size.

Let us represent scalars by `s`, vectors by `v`, matrices by `m`, and higher-rank arrays by `a`.
The table below shows the same of the result of some _inner products_:

| `r ← x f.g y` | `⍴x` | `⍴y` | `⍴r` |
| :- | -: | -: | -: |
| `a ← a f.g a` | `2 3 8` | `8 5 4` | `2 3 5 4` |
| `a ← a f.g a` | `2 3 8` | `8 3 2` | `2 3 3 2` |
| `m ← m f.g m` | `3 5` | `5 8` | `3 8` |
| `v ← m f.g v` | `4 7` | `7` | `4` |
| `v ← v f.g m` | `4` | `4 7` | `7` |
| `s ← v f.g v` | `10` | `10` | `⍬` |

(Operators-Typical-Uses-of-Inner-Products)=
### Typical Uses of Inner Products

(Operators-Two-Simple-Problems)=
#### Two Simple Problems

Many students imagine that matrix products are complex things, reserved for mathematicians, and far removed from everyday life.
This opinion should be reconsidered: very simple problems can be solved using inner product.

`hms` is a variable which contains a time interval in hours, minutes, and seconds:

In [90]:
hms ← 3 44 29

We would like to convert it into seconds.
We shall see three methods just now, and a fourth method will be given in another chapter.

A horrible solution:

In [91]:
(3600×hms[1]) + (60×hms[2]) + hms[3]

A good APL solution:

In [92]:
+/ 3600 60 1 × hms

An excellent solution with inner product:

In [93]:
3600 60 1 +.× hms

The second and third solutions are equivalent in terms of number of characters typed and similar in performance.
However, **it is recommended** that you use the third one: it will help you become familiar with _inner product_ so that after a certain period, it will become part of your toolkit as an APL programmer.

Here is a very similar example.
Two vectors represent the prices of a certain number of goods and the quantities we bought:

In [94]:
price ← 6 4.2 1.5 8.9 31 18
qty   ← 2 6   3   5   1  0.5

To calculate how much we paid, we can use the beginner's solution, or a solution with a simple _inner product_; they give the same result, of course:

In [95]:
+/ price × qty

In [96]:
price +.× qty

Just to show how it works, {numref}`fig-Inner_Product_2` contains an explanatory diagram similar to the one we used for our Banks/Investments example.

(fig-Inner_Product_2)=
```{figure} ../res/Inner_Product_2.png
---
name: Inner_Product_2
---
Diagram explaining the behaviour of an _inner product_ between two vectors
```

(Operators-A-Useful-Family)=
#### A Useful Family

Used with comparison functions, _inner product_ offers 18 extremely useful derived functions.

Here is a vector `ages` containing the ages of 400 persons:

In [97]:
⎕RL ← 73
⎕← 20↑ages ← ?400⍴100  ⍝ We display the first 20 ages only.

In the same way as we did in {numref}`Some-Primitive-Functions-Reduction-of-Binary-Data`, we can answer some elementary questions:

Are all these people younger than 65?

In [98]:
∧/ ages < 65

Is there at least one person younger than 20?

In [99]:
∨/ ages < 20

How many people are younger than 20?

In [100]:
+/ ages < 20

We can now replace _reduce_ in the previous examples by _inner product_, like this:

Are all these people younger than 65?

In [101]:
ages ∧.< 65

Is there at least one person younger than 20?

In [102]:
ages ∨.< 20

How many people are younger than 20?

In [103]:
ages +.< 20

Clever, isn't it?

These expressions can be read as:

 - `∧.<` means "all smaller" – are the ages **all smaller** than 65?
 - `∨.<` means "at least one is smaller" – is there **at least** one age **smaller** than 20?
 - `+.<` means "how many are smaller" – **how many** ages are **smaller** than 20?

In those three expressions, we have combined `∧`, `∨`, and `+` with `<`.
We could just as well combine them with all the comparison symbols, giving 18 different _inner products_, as shown in this table:

In [104]:
'∧∨+' ∘.{⍺,'.',⍵} '<≤=≥>≠'

(Operators-A-Special-Case-of-a-Comparison-Inner-Product)=
#### A Special Case of a Comparison Inner Product

In this family of _inner products_, `∧.=` is particularly interesting, because it answers the question "are all those values equal?".
For example, applied to vectors of the same length:

In [105]:
'customer' ∧.= 'customer'

In [106]:
'customer' ∧.= 'cucumber'

Let us use this property to search for a word in a matrix of words:

In [107]:
⎕← words ← 8 7⍴'CONTACTCOLUMNSFORTUNEPRODUCTCOLONELPROVIDEMACHINETYPICAL'

If we combine this 8 by 7 matrix with a 7-item vector, compatibility rules are obeyed, and the result will be a 8-item vector:

In [108]:
words ∧.= 'PRODUCT'

The shape of `words` is `8 7` and the shape of `'PRODUCT'` is `7`, so the common dimension disappears, and the result has shape `8`.

Now, let us search for three words:

In [109]:
⎕← three ← 3 7⍴'MACHINECOMFORTPRODUCT'

In [110]:
words ∧.= ⍉three

We must transpose the matrix to be compliant with the compatibility rules, and the result shows what word was found in what row of `words`.

If we wanted to know which words were found, we could add an _or-reduction_:

In [111]:
∨⌿ words∧.=⍉three

If we wanted to know which of the rows in `words` contain words in `three`, we could have used another _or-reduction_, but along the other axis:

In [112]:
∨/ words∧.=⍉three

It may also be useful to search for the positions of said matches, but we can use _index of_ for that:

In [113]:
words ⍳ three

The converse to the expression `∧.=` is `∨.≠`.
(That means that `∧.=` and `∨.≠` always return opposite Boolean values.)
It looks for _different_ values instead of looking for _equal_ values.
Let us look at one simple example:

In [114]:
words ∨.≠ ⍉three

A `1` means that this word in `three` does not match the word in this row of `words`.
So, if a row contains all `1`s, the word in that row does not match any of the words in `three`.
Using _and-reduce_ along the second axis pinpoints the rows of `words` for which this is true:

In [115]:
∧/ words∨.≠⍉three

With a compression, we can see the words that are not found in `three`:

In [116]:
(∧/words∨.≠⍉three) ⌿ words

(Operators-Similar-Applications)=
#### Similar Applications

Very often it is desirable to find out whether any rows (or columns) of a matrix contain all blanks or all zeroes; or, alternatively, whether any rows or columns contain at least one non-zero number or a non-blank character.

To solve the first task we can use the same _inner product_ as we used in most of the previous section (`∧.=`) and, to solve the second one, we can use the converse, which we introduced at the end of the previous section (`∨.≠`).

Suppose we have a matrix of characters `mc` and a matrix of numbers `mn`. Then,

 - `mc ∧.= ' '` says which rows contain all blanks;
 - `mn ∧.= 0` says which rows contain all zeroes;
 - `' ' ∧.= mc` says which columns contain all blanks;
 - `mc ∨.≠ ' '` says which rows contain at least one non-blank character;
 - `0 ∨.≠ mn` says which columns contain at least one non-zero number; and so on...

(Operators-Shortest-Routes-in-a-Graph)=
#### Shortest Routes in a Graph

Finding the shortest routes in a graph is a classical problem to which _inner product_ offers an elegant solution.
Imagine 6 points in a town.
They can be joined via a certain number of paths, according to {numref}`fig-Town_Diagram`.

(fig-Town_Diagram)=
```{figure} ../res/Town_Diagram.png
---
name: Town_Diagram
---
A diagram with connections between 6 points in a town.
```

We can create a matrix with the distances between the points.
The missing paths will be represented by a very high value (`1000` in this case) to dissuade anyone from using them:

In [117]:
⍝ to            A    B    C    D    E    F 
distances ←,    0   21 1000   35 1000 1000  ⍝ from A to ...
distances ,←   32    0   34 1000 1000 1000  ⍝ from B to ...
distances ,← 1000   34    0 1000 1000   25  ⍝ from C to ...
distances ,← 1000   44 1000    0 1000 1000  ⍝ from D to ...
distances ,← 1000 1000   51   17    0 1000  ⍝ from E to ...
distances ,← 1000 1000   31 1000   24    0  ⍝ from F to ...
⎕← distances ← 6 6⍴distances

The matrix `distances` contains distances from one point to another one, assuming we follow a single path.
The values `1000` indicate connections that cannot be made directly.
For example, there is no direct route from `E` to `B`; can we get there in two steps?

Let us consider all the possible pairs of routes from `E` to `B`:

| Routes | Distances | Total distance |
| :- | -: | -: |
| `E → A` + `A → B` | 1000 + 21 | 1021 |
| `E → B` + `B → B` | 1000 + 0 | 1000 |
| `E → C` + `C → B` | 51 + 34 | 85 |
| `E → D` + `D → B` | 17 + 44 | 61 |
| `E → E` + `E → B` | 0 + 1000 | 1000 |
| `E → F` + `F → B` | 1000 + 1000 | 2000 |

These computations could have been performed by APL.
The first set of distances considered refer to routes that start at `E`, which are the values of the fifth row of the matrix `distances`:

In [118]:
distances[5;]

Similarly, the second set of distances considered refer to routes that end at `B`, which are the values of the second column of the matrix `distances`:

In [119]:
distances[;2]

Therefore, all we have to do is sum the fifth row “from `E`” to the second column “to `B`” and we get distances of paths from `E`, with a possible intermediate stop, that end at `B`:

In [120]:
distances[5;] + distances[;2]

Only two routes really exist, because they are smaller than `1000`, which are the ones of length `85` and `61`.
Of course, we shall choose the shortest one:

In [121]:
⌊/ distances[5;]+distances[;2]

To obtain all the minimum routes that have one or two steps, we just have to repeat this calculation for all rows and columns:
an _inner product_ by the _minimum of sums_ will do that.

In [122]:
⎕← L2 ← distances ⌊.+ distances

This result shows new routes, for example from `A` to `C`, from `B` to `F`, and others.

The matrix `distances` contains zeroes in the diagonal, because the distance from a point to itself is zero.
That means that the _inner product_ computed above shows a matrix that displays the length of the shortest route between two points that makes use of one or two roads.
That is why the matrix was called `L2`.

Notice that `L2` and `distances` have some common values:

In [123]:
L2 = distances

That is because the matrix `distances` already tells us what are the shortest routes between two points that make use of a **single** road.
Typically, going directly from a starting point to your final destination is faster than going through an intermediate stop, and that is why many values in `L2` match `distances`.

If we compute yet another _inner product_, we determine the lengths of the shortest routes between two points that make use of one, two, or three roads:

In [124]:
⎕← L3 ← L2 ⌊.+ distances

Again, `L3` and `L2` have some values in common:

In [125]:
L3 = L2

The values in common refer to connections for which considering a third road doesn't help.
For example, you couldn't go from `A → C` directly, but if you go through `B`, then you can go from `A → B → C`, and the length of that path is 55.
When computing `L3`, we try to see if there is a path `A → C`, using three roads, that is faster than the path we already know.
For example, is the path `A → D → B → C` faster?
In this case, it isn't, and that is why `L3[1;3]` and `L2[1;3]` are the same:

In [126]:
L3[1;3] = L2[1;3]

Imagine, however, that better roads are built in the directions `A → D` and `D → B`:

In [127]:
newDists ← distances
newDists[(1 4)(4 2)] ← 5 5
⎕← newDists

Now, using one or two roads, you can go from `A` to `C` in:

In [128]:
(newDists ⌊.+ newDists)[1;3]

However, if we consider routes that use one, two, or three roads, we can make use of the new better roads and go from `A` to `C` faster:

In [129]:
(newDists ⌊.+ newDists ⌊.+ newDists)[1;3]

If we ignore these new roads and continue using the distances we saw before, we can do one final _inner product_ between `L3` and `distances` to figure out how to connect all points:

In [130]:
⎕← L4 ← L3 ⌊.+ distances

`L4` does not contain the value `1000`, so we see it is possible to go from any point to any point using four roads or less.
If we tried doing an additional _inner product_, we would see that all values would stay the same, which means we already know the shortest routes possible:

In [131]:
L4 ≡ L4 ⌊.+ distances

Here is a representation of all the connections:

In [132]:
' ABCDEF','ABCDEF'⍪L4

These computations using _inner product_ are elegant, but they have a shortcoming:
we found, for example, that the shortest path from `D` to `E` has length 127, and that it requires four steps, but we do not know which ones those four steps are.

(Operators-Is-a-Graph-Connected)=
#### Is a Graph Connected?

In some development projects involving large graphs, it is sometimes necessary to check whether all points can be reached from any other point.
In our town analogy from before, this would amount to checking whether we could go from any location to any other location, regardless of the length of the route.

We already know the answer for the diagram in {numref}`fig-Town_Diagram`, so let us consider a modified version in {numref}`fig-Town_Diagram_Not_Connected`:

(fig-Town_Diagram_Not_Connected)=
```{figure} ../res/Town_Diagram_Not_Connected.png
---
name: Town_Diagram_Not_Connected
---
A modified diagram with connections between 6 points.
```

To check if the graph is connected (to check if you can go from any point to any other point), we can represent connections with a `1` and absence of connections with a `0`:

In [133]:
connections ←, 1 1 0 1 0 0
connections ,← 1 1 0 0 0 0
connections ,← 0 0 1 0 0 1
connections ,← 0 1 0 1 0 0
connections ,← 0 0 1 1 1 0
connections ,← 0 0 1 0 1 1
connections ← 6 6⍴connections
' ABCDEF','ABCDEF'⍪connections

In the matrix `distances`, the diagonal was set to `0` because the distance from a point to itself was `0`.
In the matrix `connections`, the diagonal is set to `1` because each point is (obviously!) connected to itself.

The matrix `connections` determines the direct connections between points, and we can see there is no direct connection from `C` to `E`:

In [134]:
connections[3;5]

Is there a connection in two steps?
This connection will exist if we can go from `C` to `A` **and** from `A` to `E`, **or** from `C` to `B` **and** from `B` to `E`, **or** ... and so on.

Repeated for all points, this connectivity matrix in two steps can be obtained using an _inner product_ by _or_ and _and_:

In [135]:
⎕← C2 ← connections ∨.∧ connections

Now, we can see that `C` is connected to `E`:

In [136]:
C2[3;5]

We can keep computing these _inner products_:

In [137]:
⎕← C3 ← C2 ∨.∧ connections

In [138]:
⎕← C4 ← C3 ∨.∧ connections

In [139]:
⎕← C5 ← C4 ∨.∧ connections

The matrix `C5` tells what points are connected by routes with 5 steps or less.
Do we need to compute another _inner product_?

Our town has 6 different points of interest.
If you cannot go from one place to another in 5 steps, there is no point in trying 6 steps:
routes with 6 steps will mean we are repeating intermediate stops, which does not help in trying to reach a specific destination.

So, our final connectivity matrix is `C5`:

In [140]:
C5

Because it contains `0`s, it shows that we cannot go from `D` to `C`, for example.
You can confirm this by looking at {numref}`fig-Town_Diagram_Not_Connected` and realising there is, indeed, no roads that take us from `D` to `C`.

(Operators-Other-Uses-of-Inner-Product)=
### Other Uses of Inner Product

We saw above some common uses of _inner product_, but there are many other useful _inner products_ using primitives or even user-defined functions.
Learning to recognise patterns where an _inner product_ is applicable is just a matter of practice.

As for _outer product_, some applications of _inner product_ produce nested arrays, as you can see with the following examples:

In [141]:
⎕← a ← 2 3⍴2 4 1 1 3 5

In [142]:
⎕← b ← 3 4⍴3 0 2 5 1 7 7 2 6 0 4 2

In [143]:
a ,.+ b

In [144]:
a +., b

(Operators-Application)=
### Application

We have a certain number of two-dimensional points, the coordinates of which are given by a nested vector:

In [145]:
⍝ points:    A     B     C     D      E     F     G    H
coords ← (0 2)(¯1 2)(¯2 1)(¯1 0)(¯1 ¯1)(1 ¯3)(2 ¯2)(2 0)

Now, we take those coordinates and then split them into vectors with the x and y coordinates:

In [146]:
⎕← (x y) ← ↓[1]↑coords

{numref}`fig-Vertices_Polygon` shows where those points are located in a coordinate system, and the polygon we get when we connect those points:

(fig-Vertices_Polygon)=
```{figure} ../res/Vertices_Polygon.png
---
name: Vertices_Polygon
---
A polygon with eight vertices.
```

The area of the polygon can be calculated by adding the areas of the trapeziums delimited by the polygon and the horizontal axis, like the grey trapezium $[FGHK]$.
For each of those trapeziums, their base lengths are calculated by subtracting adjacent values in `x`:

In [147]:
x - 1⌽x

Then, the base lengths have to be multiplied by half of the sums of adjacent values in `y`:

In [148]:
(y + 1⌽y)÷2

In other words, we must _add_ the _products_ of bases by heights, which can be written as an _inner product_:

In [149]:
(x-1⌽x) +.× (y+1⌽y)÷2

What about the perimeter now?
We must add all the individual segment lengths.
The length of a segment $[BC]$ or $[FG]$ can be calculated using the Pythagorean theorem: $a^2 + b^2 = c^2$.

We shall calculate the length of horizontal and vertical sides by subtracting adjacent values in `x` and `y`, as we did for `x` in the previous example.

In [150]:
⎕← segs ← (x-1⌽x),[1.5](y-1⌽y)

Now, in each small right-angled triangle, we must add the squares of both sides to obtain the square of each hypotenuse: _add_ the _squares_ will be our first _inner product_:

In [151]:
segs +.* 2

Then, we have to add the square roots of these hypotenuses.
_Add_ the _square roots_ will be our second _inner product_:

In [152]:
(segs +.* 2) +.* 0.5

(fig-Inner_Product_Drawing)=
```{figure} ../res/Inner_Product_Drawing.png
---
name: Inner_Product_Drawing
---

```

(Operators-Intermission-Exercises)=
## Intermission Exercises

```{exercise}
:label: reductions
You are given the matrix `mat` shown below.

Calculate the result of the following expressions and then check your answers on the computer:

 1. `⌈/ mat`
 2. `⌊/ +/ mat`
 3. `×/ ⌊/[1] mat`
 4. `×/ ⍴mat`
```

In [153]:
mat ← 3 5⍴8 2 5 1 4 3 7 1 5 0 4 3 6 0 6

```{exercise}
:label: scans
Calculate:

 1. `-\ 6⍴1`
 2. `-\ ⌽⍳5`
 3. `×/ +\ 6⍴1`
```

```{exercise}
:label: Boolean-scans-and-reductions
Calculate:

 1. `∧/ 1 1 1 0 1 1`
 2. `∧\ 1 1 1 0 1 1`
 3. `=/ 0 1 1 1 0 1 1`
 4. `=\ 0 1 1 1 0 1 1`
```

```{exercise}
:label: reverse-engineer-scan
When we execute `×\vec`, we get the result `7 14 70 210 840`.
What is the value of `vec`?
```

```{exercise}
:label: broken-keyboard-iota
Broken keyboard!
The iota (`⍳`) key of your keyboard does not work.
How could you create the list of the first `n` integers?
```

```{exercise}
:label: triangle-area
Let $a$, $b$, and $c$, be the three sides of a triangle, and $s$ be its semi-perimeter (half of its perimeter, $s = \frac{a + b + c}2$).
Believe it or not, the area of that triangle is equal to the following expression (called “Heron's formula”):

$$\sqrt{s \times (s - a) \times (s - b) \times (s - c)}$$

Can you write a function to calculate the area of a triangle given the lengths of its sides?
Use the two examples below to validate your solution.
```

In [154]:
Area 3 4 5

VALUE ERROR: Undefined name: Area
      Area 3 4 5
      ∧

In [155]:
Area 10 6 8

VALUE ERROR: Undefined name: Area
      Area 10 6 8
      ∧

```{exercise}
:label: all-different
We would like to know whether all the items of a vector are different.
Among the many possible solutions, could you find one using _outer product_ and another one using _inner product_?
The result must, of course, be a Boolean `0` or `1`.
```

```{exercise}
:label: pairwise-reduction
What would be the result of `2 =/ 'MASSACHUSSETTS'`?
```

```{exercise}
:label: word-in-vector
Try to find a word in a vector of characters.
Your function should give the positions of the first letter of the word in the vector.

After solving this exercise once, try to _also_ implement this function `In` using an _inner product_.
Solving the next two exercises first might help.
```

In [156]:
'CAN' In 'CAN YOU CANCEL MY FLIGHT ON AIR CANADA?'

VALUE ERROR: Undefined name: In
      'CAN'In'CAN YOU CANCEL MY FLIGHT ON AIR CANADA?'
           ∧

```{exercise}
:label: find-row-in-matrix
Broken keyboard!
Try to find a row in a matrix without using dyadic iota `⍳`.
Your function `InMat` should expect a matrix on the left and a vector on the right, and it should return a Boolean value indicating whether the left argument matrix contains a row equal to the right argument vector.
You can assume the matrix has as many columns as the vector has elements.
```

In [157]:
(4 3⍴'BANCANDANDIG') InMat 'CAN'

VALUE ERROR: Undefined name: InMat
      (4 3⍴'BANCANDANDIG')InMat'CAN'
                          ∧

In [158]:
(4 3⍴⍳12) InMat 0 1 2

VALUE ERROR: Undefined name: InMat
      (4 3⍴⍳12)InMat 0 1 2
               ∧

```{exercise}
:label: in-mat-find-better
Modify the previous exercise so that the right argument can either be a vector or a matrix.
Your function should return a vector with as many elements as there are rows on the right argument (or with one element, if the right argument is a vector), where each element is a Boolean value indicating whether the corresponding row of the right argument matches any of the rows of the left argument matrix.

Can you use _inner product_ in this exercise and/or in the previous one?
```

In [159]:
(4 3⍴'BANCANDANDIG') InMat2 'CAN'

VALUE ERROR: Undefined name: InMat2
      (4 3⍴'BANCANDANDIG')InMat2'CAN'
                          ∧

In [160]:
(3 3⍴9 8 7 4 5 6 3 2 1) InMat2 2 3⍴⍳6

VALUE ERROR: Undefined name: InMat2
      (3 3⍴9 8 7 4 5 6 3 2 1)InMat2 2 3⍴⍳6
                             ∧

```{exercise}
:label: cross-count
For a certain number of people, you are given two vectors:

 1. `status` – a character vector specifying the person's marital status (Single, Married, Divorced, Widow, Unknown); and
 2. `graduated` – a character vector specifying if the person has graduated or not (Yes/No).

Write a function to count how many people are in each category.
```

In [161]:
CrossCount ← {binx ← (∪⍺)∘.=⍺ ⋄ biny ← ⍵∘.=(∪⍵) ⋄ r ← binx +.∧ biny ⋄ ((⊂''),(⊂'Total'),⍨∪⍵)⍪((⊂'Total'),⍨∪⍺),(⊢⍪+⌿)(⊢,+/)r}

In [162]:
⎕RL ← 73
⎕← 10↑status ← 'SMDWU'[?300⍴5]

In [163]:
⎕RL ← 73
⎕← 10↑graduated ← 'YN'[?300⍴2]

In [164]:
graduated CrossCount status

(Operators-At)=
## At

The operator _at_ can be used to work with values at specified positions, and there are multiple ways in which we can do this.
In its most general form, the operator _at_ can work with right arguments of arbitrary rank, but for the sake of simplicity we will start by explaining how the operator works with vectors as right arguments.

(Operators-Apply-Function-At-Indices)=
### Apply Function At Indices

In one of its forms, the operator _at_ can be used to apply a function at the specified indices of the argument vector.
The function to be applied is the left operand and the indices are the right operand.

This is the first time we learn about an operator that takes an array as the right operand.
In the example below, notice how we use parentheses to separate the right operand array from the right argument array.

Let us _negate_ the values _at_ indices `1`, `3`, and `9`, of `vector`:

In [165]:
vector ← 10×⍳10
idx ← 1 3 9
(-@idx) vector

Notice that the operator _at_ returns the whole array after modifying the specified values, in opposition to returning just the values that were modified.

The parentheses around `-@idx` are necessary.
If they were not there, APL would not complain, but it would produce some interesting output:

In [166]:
-@idx vector

What is happening is that APL is looking at `idx vector` as a vector of length two defined by strand notation.
We can verify that `idx vector` is being interpreted as a single array.
We do that by parenthesising `idx vector` and noticing that the interesting output does not change:

In [167]:
-@(idx vector)

The exact meaning of this output will be explained in {numref}`Tacit-Programming-Inspecting-Tacit-Functions`.
For now, it suffices to understand that it does _not_ the output of `(-@idx) vector`.

In order for APL to know that `idx` is the right _operand_ and `vector` is the right _argument_, we must separate them in some way.
Parenthesising the operator and its operand is one option, but another common option is to just use a _right tack_:

In [168]:
-@idx ⊢ vector

The _right tack_ works because it effectively breaks the strand, which lets the operator _at_ understand that its right operand is just `idx`.

Below, you can find another example usage of the operator _at_, in which we double values _at_ the indices `1` and `10` with a dfn:

In [169]:
{⍵×2}@1 10⊢ vector

The example above also shows that the operator _at_ works with user-defined functions.

It is important to understand how the operator _at_ passes the elements of the indices specified into the left operand function.
Take a look at the definition of the nested vector below:

In [170]:
⎕← nested ← ⍳¨⍳5

What is the output you expect from running the expression `(⍴@4 5)nested`?
Give it some thought...
Because the actual result might surprise you:

In [171]:
⍴@4 5⊢nested

The operator _at_ collects all the elements at the indices specified and then passes them, as a whole vector, to the left operand function.
We can see this by using, as the left operand, a dfn that prints its right argument:

In [172]:
_ ← {⎕←'called with ⍵: ' ⋄ ⎕←⍵ ⋄ ⍵}@4 5⊢nested

This is different from passing each element to the left operand function separately when the left operand function is **not** a _scalar function_, like `⍴`.

Then, after all the values are collected and passed in to the left operand function, the result should be a single scalar (that gets placed in all the indices specified) or a vector with as many elements as there were indices.
In that case, the elements of the result vector are distributed across the positions specified by the indices.

The example above with _shape at_ and the nested vector shows that a scalar result gets placed in all the positions that were specified.
The example below shows that the result vector must have as many elements as there were indices, otherwise the operator _at_ will not know how to place the results:

In [173]:
⎕← matrices ← {⍵ ⍵⍴⍳⍵*2}¨⍳3

In [174]:
⍴@3⊢matrices

LENGTH ERROR
      ⍴@3⊢matrices
      ∧

The reason we get a `LENGTH ERROR` above is that the _shape at index `3`_ returns `3 3`, which is a vector of length `2`, which does not match the length `1` of the vector of indices.

(Operators-Apply-Dyadic-Function-At-Indices)=
### Apply Dyadic Function At Indices

When the function in `(F@idx)vector` is dyadic, the left argument of `F` can be written on the left of the operator _at_, as `left (F@idx) vector`.
In this case, the operator _at_ does not do any sort of selection or indexing into the left argument.
The left argument is passed directly to the function `F`:

In [175]:
10 100 ×@3 5 ⊢ vector

Thus, if the function `F` is a scalar function, the left argument must be a scalar or have the same length as the vector of indices:

In [176]:
10 100 1000 ×@3 5 ⊢ vector

LENGTH ERROR: Mismatched left and right argument shapes
      10 100 1000×@3 5⊢vector
                 ∧

In [177]:
100 ×@1 3 5 ⊢ vector

(Operators-Replace-Values-At-Indices)=
### Replace Values At Indices

Here is the nested vector from before:

In [178]:
nested

Can you use a dfn to replace the elements of `nested` at indices `3` and `5` with the vectors `'CAT'` and `'DOG'`, respectively?

There are a couple of ways to do this.
For example, we can set the left operand to be a function that returns the left argument, and pass the new values as the left argument:

In [179]:
'CAT' 'DOG'{⍺}@3 5⊢nested

This is equivalent to just enclosing the new values in a dfn in the left operand:

In [180]:
{'CAT' 'DOG'}@3 5⊢nested

The operator _at_ can, indeed, be used to replace values at the specified indices.
We used a couple of different functions to do that, but the operator _at_ provides a special form, in which the left operand is an array instead of a function.

Suppose we have a vector `vec` and a vector with some indices, `idx`.
If the vector `new` has the same length as `idx`, then we have seen that `({new}@idx)vec` puts the elements of the vector `new` in the positions specified by the indices `idx`, but we can actually do this more directly by writing `(new@idx)vec`.
That is, the operator _at_ can take a vector on the left, instead of a function, and it will put those values in the positions specified:

In [181]:
'CAT' 'DOG'@3 5⊢nested

The operator _at_ has another form that we discuss next.

(Operators-Right-Operand-as-Selector)=
### Right Operand as Selector

So far, the forms we have seen with the operator _at_ had an array right operand (more specifically, a vector).
The operator _at_ can also take a right operand selector function.
This function must return a Boolean mask that determines to which values the left operand is applied.

For example, the code below replaces all values larger than 5 with the value 0:

In [182]:
⎕← vector ← 10?10

In [183]:
IsLarger5 ← {⍵>5}

In [184]:
0@IsLarger5⊢ vector

When the right operand is a function, that function must be prepared to receive the whole right argument array at once.
In other words, the selector function is not applied individually to each element of the right argument.

So, if we define `LongerThan3`:

In [185]:
LongerThan3 ← {3<≢⍵}

And if we recall the vector `nested`:

In [186]:
nested

We might have expected `({3↑⍵}@LongerThan3) nested` to trim the two last vectors.
Instead, it raises an error:

In [187]:
{3↑⍵}@LongerThan3⊢ nested

RANK ERROR: Right operand and argument ranks differ
      {3↑⍵}@LongerThan3⊢nested
           ∧

The error happens because `LongerThan3` takes the whole vector `nested` as its argument and produces a scalar result, the Boolean value `1`:

In [188]:
LongerThan3 nested

Then, the operator _at_ sees that result as the Boolean mask that will determine what values get passed in to the left operand function.
However, the Boolean mask is just a scalar `1` and the right argument is a vector, so there is a rank mismatch and the operator _at_ cannot do its magic.
If we modify the function `LongerThan3` to return its result as a vector, we would still have an error, but this time a `LENGTH ERROR`:

In [189]:
LongerThan3 ← {,3<≢⍵}
{3↑⍵}@LongerThan3⊢ nested

LENGTH ERROR: Right operand and argument lengths differ
      {3↑⍵}@LongerThan3⊢nested
           ∧

This time, the error is a `LENGTH ERROR` because the Boolean mask is the vector `,1` which has length `1`, whereas the argument vector `nested` has length `5`.

As we have seen, the operator _at_ is very versatile.
As a right operand, you can have:

 - the set of indices where you want to do some work; or
 - a selector function that produces a Boolean mask indicating the positions where you will do some work.

As a left operand, you can have:

 - a function to be applied to the subarray that was selected; or
 - new values to replace the subarray that was selected.

The left operand acts on the selection of the right operand.

(Operators-At-with-High-Rank-Arguments)=
### At with High-Rank Arguments

So far, all of our examples with the operator _at_ were with vectors.
However, the operator _at_ can handle right arguments of arbitrary rank.
We just need to understand how those high-rank arrays are handled by the operands of the operator _at_.

(Operators-Right-Operand-Array)=
#### Right Operand Array

The right operand array can be a simple integer vector or a nested integer vector.
If it is a simple integer vector (or a simple integer scalar), then the integers are the indices of major cells of the argument.

For example, we can easily increment the second and fourth rows of a matrix:

In [190]:
⎕← mat ← 4 4⍴⍳16

In [191]:
1000 +@2 4⊢ mat

If the right operand is nested, it specifies indices for _reach_ or _choose_ indexing.

For example, below we negate the four corners of our matrix `mat`:

In [192]:
-@((1 1)(1 4)(4 1)(4 4))⊢mat

(Operators-Right-Operand-Function)=
#### Right Operand Function

When the right operand is a function, it must still compute a Boolean mask that determines what values will be modified or replaced.

For example, we can easily add one to the odd values in the matrix:

In [193]:
1 +@{2|⍵} mat

(Operators-Shape-of-the-Left-Operand)=
#### Shape of the Left Operand

So far, all the examples that we saw and that involved high-rank arrays avoided the issue of shapes:

 - If the left operand is a function, what will be the shape of its argument?
 - If the left operand is an array, what should its shape be for _at_ to know how to replace the values?

Before you proceed and read this section, try to do some experiments to see if you can deduce these rules on your own.

Ready?

1. If the right operand is an array that specifies indices and the left operand is an array of replacement values, then the shape of the left operand must conform to the shape induced by the right operand.

If the right operand is an integer vector specifying major cells, the left operand must be of the same rank as the right argument, and it must have as many major cells as the length of the right operand:

In [194]:
(100+3 4⍴⍳4)@2 3 4⊢mat  ⍝ 3 indices, left operand has 3 rows.

If the right operand is a nested array that uses _reach_ or _choose indexing_ to select which values will be replaced, then the left operand must have the same shape as the array of indices:

In [195]:
corners ← (1 1)(1 4)(4 1)(4 4)

In [196]:
(⍳4)@corners⊢mat  ⍝ vector ←→ vector

In [197]:
(2 1 2⍴⍳4)@(2 1 2⍴corners)⊢mat  ⍝ 2 1 2 cuboid ←→ 2 1 2 cuboid

2. If the right operand is an array that specifies indices and the left operand is a function, then the right argument of the function will have the shape induced by the right operand (as seen in the previous case) and it must return an array of the same shape.

If we use _choose indexing_ with a two by two matrix to select the corners of our matrix `mat`, then the right argument of the left operand will be a two by two matrix and so must be the return value:

In [198]:
{⎕←'right arg:'⍵ ⋄ 2 2⍴⍳4}@(2 2⍴corners)⊢mat

Similarly, if we use a simple integer vector `vec` to select major cells of `array`, the right argument of the left operand will have shape equal to `(⍴vec),1↓⍴array` and the return value should have the same shape:

In [199]:
{⎕←'shape:'(⍴⍵) ⋄ 2 4⍴⍳4}@(2 3)⊢mat

3. If the right operand is a function that computes a Boolean mask, the values that are selected will be ravelled into a vector.
   1. If the left operand is a replacement array, such an array must be a vector with the same length as the ravel of the selected values.
   2. If the left operand is a function, its right argument will be the ravel of the values selected and it must return a vector with the same length.

The only exception to these two bullet points is if the left operand array is a scalar or if the left operand function returns a scalar.
In that case, all the values selected will be replaced by that scalar.

Let us demonstrate these rules by using the operator _at_ on the matrix `mat`:

In [200]:
mat

We will be working on the central two by two region of the matrix:

In [201]:
mat ∊ 6 7 10 11

We can replace those four values with four other values, if those are in a vector:

In [202]:
(100×⍳4)@{⍵∊6 7 10 11}mat

We can transform those four values, as long as the left operand returns a vector of length four:

In [203]:
{1⌽⍵}@{⍵∊6 7 10 11}mat  ⍝ transform those 4 values

The left operand can also be, or return, a scalar.
In that case, the scalar will replace all the selected values:

In [204]:
0@{⍵∊6 7 10 11}mat  ⍝ replace all with 0

(Operators-Rank-Operator)=
## Rank Operator

The operator _rank_ is represented by the character jot diaeresis `⍤`, and you can type it with the keys <kbd>APL</kbd>+<kbd>Shift</kbd>+<kbd>J</kbd>.
A good mnemonic is that it is the jot (<kbd>APL</kbd>+<kbd>j</kbd>) with something on top (<kbd>Shift</kbd>).

The operator _rank_ is a powerful operator that allows you to apply functions to sub-arrays of your argument arrays.
The function to be applied is the left operand `F` and the sub-arrays to which `F` is applied are defined by the right operand `spec`.

(Operators-Sub-Arrays-in-the-Monadic-Case)=
### Sub-Arrays in the Monadic Case

Typically, the best way of helping new learners grasp how the operator _rank_ works is by exploring the result of `⊂⍤spec` for various integer scalars `spec` and for the case where `⊂⍤spec` is used monadically.

With that in mind, we define a cuboid below:

In [205]:
⎕← cuboid ← 2 3 4⍴⍳24

The operator _rank_ in `⊂⍤spec ⊢ cuboid` will apply the function _enclose_ to the cells of `cuboid` that have rank specified by `spec`:

 - if `spec` is `0`, the operator _rank_ will enclose all the scalars in the cuboid because scalars have rank `0`;
 - if `spec` is `1`, the operator _rank_ will enclose all the rows of the cuboid because rows have rank `1`;
 - if `spec` is `2`, the operator _rank_ will enclose all the planes / sub-matrices in the cuboid because planes have rank `2`; and
 - if `spec` is `3` or more, the operator _rank_ will enclose the whole cuboid because the cuboid has rank `3`.

In [206]:
⊂⍤3⊢cuboid

In [207]:
⊂⍤2⊢cuboid

In [208]:
⊂⍤1⊢cuboid

In [209]:
⊂⍤0⊢cuboid

As these examples show, the operator _rank_ led the function _enclose_ (its left operand) to the sub-arrays that had the rank that was chosen by the right operand.

Suppose that we wanted to transpose each of the two sub-matrices of the cuboid.
One can achieve that effect with dyadic transpose, but we can also look at that as _transpose rank 2_, which means we transpose the cells that have rank 2:

In [210]:
⍉⍤2⊢cuboid

(Operators-Sub-Arrays-in-the-Dyadic-Case)=
### Sub-Arrays in the Dyadic Case

The derived function of the operator _rank_ can also be used dyadically.
In that case, the operator _rank_ will pair up sub-arrays of the left argument with sub-arrays of the right argument.
The sub-arrays of both sides do **not** have to be of the same rank.

In general, the dyadic case looks like `left (F⍤i j) right`.
The integer scalar `i` determines the rank of the sub-arrays of the left argument `left` and the integer scalar `j` determines the rank of the sub-arrays of the right argument `right`.

In order for the operator _rank_ to be able to pair up sub-arrays of the left argument with sub-arrays of the right argument, there has to be some shape compatibility:
the _frames_ of the left and right argument must be the same.
The _frames_ are composed of the leading axes of the arguments that are not included in the sub-arrays:

 - the _frame_ of the left argument is `fl ← (-i)↓⍴left`; and
 - the _frame_ of the right argument is `fr ← (-j)↓⍴right`.

So, `left F⍤i j ⊢ right` only works if `fl ≡ fr`, that is, if `((-i)↓⍴left)≡((-j)↓⍴right)`.

For example, suppose `left` has rank `5` and shape `2 3 4 5 6` and `right` has rank `4` and shape `2 4 3 8`:

In [211]:
left ← 2 3 4 5 6⍴0
right ← 2 4 3 8⍴0

 - the expression `left F⍤4 3 ⊢ right` is a valid usage of the operator _rank_ because:
    - the _frame_ of `left` is `2`, which is `¯4↓⍴left`; and
    - the _frame_ of `right` is also `2`, which is `¯3↓⍴right`.

In [212]:
_← left {⍺ ⍵}⍤4 3 ⊢ right  ⍝ works without error

 - the expression `left F⍤4 2 ⊢ right` does not work and gives a `RANK ERROR` because the _frames_ of the left and right arguments do not have the same rank:
    - the _frame_ of `left` is `2`, which is `¯4↓⍴left`; and
    - the _frame_ of `right` is `2 4`, which is `¯3↓⍴right`.

In [213]:
_← left {⍺ ⍵}⍤4 2 ⊢ right  ⍝ RANK ERROR

RANK ERROR
      _←left{⍺ ⍵}⍤4 2⊢right  ⍝ RANK ERROR
                 ∧

 - the expression `left F⍤3 2 ⊢ right` does not work and gives a `LENGTH ERROR` because the _frames_ of the left and right arguments do not have the same axes lengths:
    - the _frame_ of `left` is `2 3`, which is `¯3↓⍴left`; and
    - the _frame_ of `right` is `2 4`, which is `¯2↓⍴right`.

In [214]:
_← left {⍺ ⍵}⍤3 2 ⊢ right  ⍝ LENGTH ERROR

LENGTH ERROR: It must be that either the left and right frames match or one of them has length 0
      _←left{⍺ ⍵}⍤3 2⊢right  ⍝ LENGTH ERROR
                 ∧

The error message above shows one more situation in which the operator _rank_ works.
If the sub-arrays of the left argument match the whole left argument or if the sub-arrays of the right argument match the whole right argument, then the operator _rank_ will pair that argument with all the sub-arrays of the other argument.

 - the expression `left F⍤5 j ⊢ right` works for any value of `j` because the frame of `left` is `⍬` and therefore has length zero.

In [215]:
_← left {⍺ ⍵}⍤5 0 ⊢ right  ⍝ works!
_← left {⍺ ⍵}⍤5 1 ⊢ right  ⍝ works!!
_← left {⍺ ⍵}⍤5 2 ⊢ right  ⍝ works!!!
_← left {⍺ ⍵}⍤5 3 ⊢ right  ⍝ works!!!!

Similarly,

 - the expression `left F⍤i 4 ⊢ right` works for any value of `i` because the frame of `right` is `⍬` and therefore has length zero.

In [216]:
_← left {⍺ ⍵}⍤0 4 ⊢ right  ⍝ works!
_← left {⍺ ⍵}⍤1 4 ⊢ right  ⍝ works!!
_← left {⍺ ⍵}⍤2 4 ⊢ right  ⍝ works!!!
_← left {⍺ ⍵}⍤3 4 ⊢ right  ⍝ works!!!!
_← left {⍺ ⍵}⍤4 4 ⊢ right  ⍝ works!!!!!

To illustrate better how the pairing of the operator _rank_ works, we can consider the dfn `{⍺ ⍵}` that will strand the left and right sub-arrays.

First, we will pair all sub-matrices on the left with all scalars on the right.

In [217]:
(3 4 5⍴⎕A) {⍺ ⍵}⍤2 0 ⊢ ⍳3

Now, we will pair all rows on the left with the right argument vector.

In [218]:
(3 4 5⍴⎕A) {⍺ ⍵}⍤1 1 ⊢ ⍳3

Notice how, in the example above, the right argument vector was repeated 12 times, one for each of the sub-arrays of the left argument.

(Operators-Cells)=
### Cells

The sub-arrays of rank `r` of an array are typically referred to as `r`-cells of that array.

 - `0`-cells are scalars;
 - `1`-cells are vectors and sometimes referred to as rows;
 - `2`-cells are matrices and sometimes referred to as planes or tables;
 - ...

So, the expression `F⍤k ⊢ array` can be said to apply `F` to the `k`-cells of `array`.
We can say the same thing the other way around: the `k`-cells of `array` are its sub-arrays on the last `k` axes.

(Operators-Negative-k)=
#### Negative `k`

If `k` is negative, a `k`-cell of an array of rank `r` is the same as a `r+k`-cell.
Using negative values of `k` can be advantageous because this makes it so that the actual rank of the cell depends on the rank of the original array.
For example, a `¯2`-cell on a matrix is actually a `(2+¯2)`-cell (a scalar), and a `¯2`-cell on a cuboid is actually a `(3+¯1)`-cell (a vector).

(Operators-Major-Cells)=
#### Major Cells

`¯1`-cells are commonly referred to as _major cells_ because they are the largest cells of an array, as far as rank is considered.
Below, you can find a table with common arrays and the corresponding major cells.

| Array | Major cells are... |
| :- | :- |
| vector | scalars |
| matrix | vectors |
| cuboid | matrices |
| 4D array | cuboids |

(Operators-Specifying-Cells)=
### Specifying Cells

Now that we are aware of what _cells_ are, the operator _rank_ can actually be defined in terms of _cells_ of the left and right arguments.

The expression `F⍤k ⊢ right` will apply the function `F` monadically to the `k`-cells of `right` and the expression `left F⍤i j ⊢ right` will apply the function `F` dyadically between the `i`-cells of `left` and the `j`-cells of `right`.
In particular, the operator _rank_ can deal with _cell_ specifications that have negative numbers.

For example, the expression `⊂⍤¯1` turns any array into a vector of its _major cells_.

If we have a matrix:

In [219]:
3 3⍴⍳9

we get a vector of its rows:

In [220]:
⊂⍤¯1 ⊢ 3 3⍴⍳9

And if we have a cuboid:

In [221]:
2 3 4⍴⍳24

we get a vector of its sub-matrices:

In [222]:
⊂⍤¯1 ⊢ 2 3 4⍴⍳24

The operator _rank_ has another form that contemplates the monadic and dyadic uses of the derived function in one single _cell_ specification, but we will only cover it in {numref}`Operators-The-Full-Rank-Specification`.

(Operators-Key)=
## Key

The operator _key_ is represented by the glyph `⌸` and you can type it with <kbd>APL</kbd>+<kbd>Shift</kbd>+<kbd>K</kbd>.
It is easy to remember the keyboard shortcut for _key_ because _key_ is in the letter K.

The operator _key_ is monadic and its left operand must always be a dyadic function that returns a result.
The derived function can be used monadically or dyadically.
In both cases, the idea is that the operator _key_ provides a way to group your values before applying `F` to each of those groups.

The expression `groups F⌸ values` will apply `F` to subsets of the _major cells_ of `values` as defined by the _major cells_ of `groups`.

Setting `F ← {⍺ ⍵}` and defining simple vectors for `groups` and `values` should bring some clarity to the way _key_ works.

Let us define two vectors that contain the suits and values of some playing cards:

In [223]:
values ← '4' 'Jack' '6' 'Ace' '10'
suits ← 'Spades' 'Hearts' 'Spades' 'Clubs' 'Spades'

Now, we can group the cards by their suits:

In [224]:
suits {⍺ ⍵}⌸ values

As we can see, the function `{⍺ ⍵}` received, as left argument, each of the unique groups, also referred to as keys.
Its right argument was a vector with all the values that were associated with each key.

The monadic case `F⌸ array` is equivalent to the dyadic case `array F⌸ ⍳≢array`.
In other words, in the monadic case, the operator _key_ uses the _major cells_ of the argument as keys and then groups together the indices where each key appears:

In [225]:
{⍺ ⍵}⌸ 'MISSISSIPPI'

In [226]:
'MISSISSIPPI',[0.5]⍳11

(Operators-Key-with-High-Rank-Arguments)=
### Key with High-Rank Arguments

The explanation above mentioned _major cells_ and _arrays_ in general because the operator _key_ **can** be used with arrays of arbitrary rank as both arguments.

To showcase this ability, consider a matrix with names of some employees and the respective days they showed up for work:

In [227]:
⎕← employees ← ↑'ALICE' 'BOB' 'ALICE' 'BOB' 'CHARLES' 'ALICE' 'CHARLES'

In [228]:
dates ← '27/6' '27/6' '28/6' '29/6' '29/6' '30/6' '30/6'

We can group the employees by workday with the operator _key_:

In [229]:
dates {⍺ ⍵}⌸ employees

We can see that using a matrix as the right argument was not a problem.
What is more, we can see that because the right argument of `{⍺ ⍵}⌸` had rank two, the right argument of the operand of _key_ also receives arguments of rank two.

If the dates had been a 2-column matrix with day and month, _key_ would still know how to group the employees:

In [230]:
⎕← datesMat ← 7 2⍴27 6 27 6 28 6 29 6 29 6 30 6 30 6

In [231]:
datesMat,employees

In [232]:
datesMat {⍺ ⍵}⌸ employees

In the example above, the operator _key_ used the _major cells_ of the left argument (its rows) to determine which keys to use.
The left argument of the operand is always the key itself, so the left argument of the operand in the example above was the 2-element vector with the day and the month.

If we want to keep only the day of employment, since all records are relative to the month of June, we can extract it with `⊃⍺`:

In [233]:
datesMat {(⊃⍺) ⍵}⌸ employees

(Operators-Order-of-the-Result)=
### Order of the Result

The elements of the result of _key_ appear in the same order as they appear in the argument vectors.
This means that if the arguments are reordered, the result of applying _key_ might also come in a different order:

In [234]:
{⍺ ⍵}⌸ 'MISSISSIPPI'

In [235]:
{⍺ ⍵}⌸ 2⌽'MISSISSIPPI'

The sub-sections that follow will cover a couple of common use-cases for the operator _key_.

(Operators-Applications-of-Key)=
### Applications of Key

(Operators-Counting-Unique-Values)=
#### Counting Unique Values

One of the simplest and most common use cases for _key_ is to count unique values in a vector, or unique _major cells_ in any arbitrary array.

For example, we can quickly compute how many of each letter a word or sentence has:

In [236]:
{⍺(≢⍵)}⌸ 'MISSISSIPPI'

In [237]:
{⍺(≢⍵)}⌸ 'HOW ARE YOU DOING TODAY'

If you are counting occurrences of values of a predetermined number of categories, bear in mind that categories that are not represented will not show up with a zero in its count.

For example, we had some playing cards before:

In [238]:
values,⍪suits

None of the cards is of the suit diamonds, so when we count how many cards of each suit, we will not have a `'Diamonds' 0` in the result:

In [239]:
{(⊃⍺)(≢⍵)}⌸ suits

After all, the operator _key_ cannot guess that the key `'Diamonds'` was missing.
If you want all possible keys to show up, catenate them once to the argument array and then subtract one from the count.
If you catenate all the possible keys in the beginning, you can even force the order of the result:

In [240]:
allSuits ← 'Clubs' 'Diamonds' 'Hearts' 'Spades'
{(⊃⍺)(¯1+≢⍵)}⌸ allSuits,suits

Notice how the order of the vector `allSuits` was preserved in the rows of the result.

(Operators-Summarising-Data-by-Category)=
#### Summarising Data by Category

The operator _key_ can also be used to aggregate and summarise data by one or more keys.
For example, suppose you have a log of purchases and sales of shares of different companies:

In [241]:
companies ← ↑'GOOG' 'MSFT' 'TSLA' 'MSFT' 'GOOG' 'GOOG' 'TSLA' 'GOOG' 'TSLA'
trades ← 100 120 80 ¯30 50 ¯100 ¯80 50 100
companies,trades

By using the operator _key_, we can easily aggregate the trades by company and then determine how many shares of each company we have:

In [242]:
companies {⍺(+/⍵)}⌸ trades

In this particular example, we used `+/` to sum all of the trades that pertained to a single company.
This pattern of aggregating data and then summarising it works with every other summarising function you can think of.

For instance, if instead of trades we had data about the prices of the stock, we could easily determine what was the highest price each company attained:

In [243]:
companies ← ↑'TSLA' 'MSFT' 'GOOG' 'GOOG' 'GOOG' 'MSFT' 'TSLA' 'MSFT' 'TSLA'
prices ← 209.39 329.37 143.77 137.88 134.17 294.95 288.12 259.58 271.71
companies,prices

In [244]:
companies {⍺(⌈/⍵)}⌸ prices

(Operators-Stencil)=
## Stencil

(Operators-Your-First-Stencil)=
### Your First Stencil

The operator _stencil_ is represented by the glyph `⌺` and it is typed with <kbd>APL</kbd>+<kbd>Shift</kbd>+<kbd>\`</kbd>.
_Stencil_ `⌺` and the _diamond_ `⋄` are in the same key, so use the fact that the _stencil_ looks like a _quad_ `⎕` around the _diamond_ `⋄` as a mnemonic to know where _stencil_ is.

The operator _stencil_ is used to apply a function operand to rectangular sections of the argument array.
The size and positioning of these rectangular sections is determined by the right operand of _stencil_ and the left operand is the function that is applied to each section.

For example, we can have a 4 by 4 matrix and we can use the operator _stencil_ to apply any given function to all its 3 by 3 sub-matrices.
Before doing any computations with the sub-matrices, we can study how the operator _stencil_ works and visualise what sub-matrices are created.
To do that, we need to:

 - use the dfn `{⊂⍵}` as the left operand, which will _enclose_ each sub-matrix and allow us to visualise all of them;
 - use the vector `3 3` as the right operand, which will tell the operator _stencil_ that we want sub-matrices that have shape `3 3`; and
 - use a matrix as the right argument to the derived function.

Here is an example:

In [245]:
⎕← mat ← 4 4⍴⍳16

In [246]:
{⊂⍵}⌺3 3⊢mat

Notice that some sub-matrices in the result above contain zeroes that were not present in the original matrix.
These rows and columns of zeroes are padding.
Padding is needed because the operator _stencil_ creates sub-matrices centred on successive elements of the matrix `mat`.
However, you can only create a 3 by 3 matrix centred around `1` (the top-left number in `mat`) if you add a column of zeroes on the left of `mat` and a row of zeroes on the top of `mat`.

The result of using the operator _stencil_ with the left operand `{⊂⍵}` can be intuitively described as the effect you get by placing a window of size `3 3` over the matrix `mat`, and then sliding that window over the matrix.
The padding is what you "see" when the window is slightly off the matrix.

(Operators-Padding-and-Window-Size)=
### Padding and Window Size

As we have seen, the operator _stencil_ sometimes adds padding to allow for the creation of sub-arrays centred on the successive elements of the argument array.
However, the padding that is added depends on the size of the sub-arrays that are created, sometimes referred to as the size of the sliding window.
If the sliding window is very big, the padding increases.
If the sliding window is very small, the padding decreases.

The total padding added does not depend on the size of the argument array.
Below, we stick to the window size of `3 3` and use a larger matrix, and we see the padding remains the same:

In [247]:
{⊂⍵}⌺3 3⊢6 6⍴⍳36

With a window size of `3 3`, the padding we get is still one row and one column around the matrix argument.

If we make the window size smaller, we get less padding.
With a unit length window (the smallest window possible), we actually get absolutely no padding:

In [248]:
{⊂⍵}⌺1 1⊢6 6⍴⍳36

If we make the window larger, we get more padding:

In [249]:
{⊂⍵}⌺5 5⊢6 6⍴⍳36

The examples before all had an odd window size, but window sizes can also be even.
When the window size is odd, it is easier to see which number a window is centred on.
If the window size `s` is even, the central element is at the index `s ÷ 2`.

Let us use a window size of 4 and look at the very first sub-matrix of `mat`:

In [250]:
⊃ {⊂⍵}⌺4 4⊢mat

The window size is `4 4` and the first window is centred around `1`, which is at index `2 2` of the sub-matrix:

In [251]:
(⊂2 2)⊃ ⊃ {⊂⍵}⌺4 4⊢mat

Let us look at all the sub-matrices:

In [252]:
{⊂⍵}⌺4 4⊢mat

When the window size is even, the padding we get seems to be the same as if the window size had been odd, and one less.
In this particular example, a window size `4 4` used the same padding as a window size `3 3`.

In general, when the window size is even, the maximum amount of padding we see is one row/column less than half of the window size.
In the example above, the window size is `4 4`, so the maximum padding we get is one less than half of that: half of that is `2 2` and one less is `1 1`, so the maximum padding we get is one row and one column.

If we go back to the larger matrix, we can try having a window size of `6 6`, to see that the maximum padding we get is `2 2`:

In [253]:
⊃ {⊂⍵}⌺6 6⊢6 6⍴⍳36

The window does not have to be a square, so we can even pick different lengths for the number of rows and columns of each sub-matrix.
As a result, the padding is also done independently for rows and columns.

We can split a matrix into sub-matrices that contain a single row and three columns, in which case there will be no padding added on top or on the bottom, but there will be padding on the left and on the right:

In [254]:
{⊂⍵}⌺1 3⊢mat

In its general form, if the window size is `ws`, then the padding you will get is `⌊(ws-1)÷2`.

If we set `ws` to the example above:

In [255]:
ws ← 1 3

We get a confirmation that the padding was `0 1`:

In [256]:
⌊(ws-1)÷2

(Operators-The-Left-Operand-Function)=
### The Left Operand Function

The operator _stencil_ takes a left operand function.
So far, we only used `{⊂⍵}` but that can be any dyadic function that returns a result.
The right argument of that function is the sub-array that the operator _stencil_ computed and the left argument gives you padding information.
In fact, the left argument `⍺` is such that `⍺↓⍵` is a sub-array without padding.
In other words, the left argument of the left operand is the value you would need if you wanted to _drop_ the padding from all sub-arrays.

Here are all the 3 by 3 sub-matrices of `mat`, with and without the padding that the operator _stencil_ adds:

In [257]:
({⊂⍵}⌺3 3⊢mat)({⊂⍺↓⍵}⌺3 3⊢mat)

We can also try pairing the left and right arguments to see what `⍺` looks like:

In [258]:
{⊂⍺ ⍵}⌺3 3⊢mat

The definition of the left argument of the left operand also determines the maximum window size for any given array.
Recall that the left argument is:

 > “the vector `⍺` such that `⍺↓⍵` removes all padding from `⍵`.”

The primitive _drop_ can drop from the beginning or end of any axis, but never from both ends at the same time.
For example, if you had the vector `0 0 1 2 3 0` you could _drop_ all the zeroes in it by dropping two from the front and one from the back, but you always have to do that by using _drop_ twice:

In [259]:
2↓¯1↓0 0 1 2 3 0

In [260]:
¯1↓2↓0 0 1 2 3 0

There is no left argument you can pass to _drop_ that will let you get rid of the leading and trailing zeroes at the same time.
Thus, the maximum window size, is the window size that ensures there is _never_ padding on both sides of a sub-array.
This is always `1+⍴array`.

For example, here is a 3 by 7 matrix:

In [261]:
⎕← letters ← 3 7⍴⎕A

For this matrix, the maximum window size is:

In [262]:
1+⍴letters

Notice, however, that this maximum is per axis.
That is, a valid window size for the matrix `letters` must be less than or equal to `4 8` in each axis.
So, a window size `ws` is valid if `ws ∧.≤ 4 8`.
Conversely, a window size `ws` is invalid if `ws ∨.> 4 8`.

Here are some examples of invalid window sizes that raise `DOMAIN ERROR`:

In [263]:
ws ← 5 6
ws ∨.> 4 8

In [264]:
{⊂⍵}⌺ws⊢letters

DOMAIN ERROR
      {⊂⍵}⌺ws⊢letters
         ∧

In [265]:
ws ← 2 10
ws ∨.> 4 8

In [266]:
{⊂⍵}⌺ws⊢letters

DOMAIN ERROR
      {⊂⍵}⌺ws⊢letters
         ∧

In [267]:
ws ← 7 12
ws ∨.> 4 8

In [268]:
{⊂⍵}⌺ws⊢letters

DOMAIN ERROR
      {⊂⍵}⌺ws⊢letters
         ∧

Finally, here is the example that makes use of the largest possible window size:

In [269]:
{⊂⍵}⌺4 8⊢letters

Notice how the nested matrices in columns 3 and 4 contain the whole matrix `letters`, plus a row and a column of padding.
That shows that the padding is already at a maximum.

(Operators-Stencil-For-Any-Rank)=
### Stencil For Any Rank

The operator _stencil_ can be applied to arrays of any rank.
The right operand array, which is responsible for determining the shape of the resulting sub-arrays, must contain as many elements as there are axes in the right argument.

In the examples above, we applied the operator _stencil_ to matrices, which have rank two, which explains why the window size was always a vector with two integers.
If we want to apply _stencil_ to a vector (rank 1), then the right operand must have a single element:

In [270]:
{⊂⍵}⌺3⊢⍳10

And if we want to apply _stencil_ to a cuboid (rank 3), then the right operand must have three elements:

In [271]:
{⊂⍵}⌺3 3 3⊢2 2 2⍴⍳24

(Operators-Step-Size)=
### Step Size

The operator _stencil_ defaults to creating all sub-matrices consecutively, but you can specify a step size that determines by how much the rectangular window moves.
The step size is also indicated in the right operand, which in its most general form is a 2-row matrix:

 - the first row determines the window size along each axis; and
 - the second row determines the step size along each axis.

The first sub-array is always centred on the first element of the argument to _stencil_, so the step size only influences the subsequent sub-arrays that are created:

In [272]:
⎕← mat ← 3 3⍴⍳9

In [273]:
ws ← 3 3

The default step size is 1 on each axis:

In [274]:
stepSize ← 1 1
⎕← complete← {⊂⍵}⌺(2 2⍴ws,stepSize)⊢mat

The step size is specified independently for each axis, so we can increase the step size along the first axis to 2.
This will skip every other row of sub-matrices:

In [275]:
stepSize ← 2 1
{⊂⍵}⌺(2 2⍴ws,stepSize)⊢mat

Notice how the two rows of the result above are the first and third rows of the nested matrix `complete`.

We can increase the step size even further, to 3.
With a step size of 3 for the first axis, we only get one out of every three rows of the output.
Because the matrix `complete` only has 3 rows, this means our result will have a single row (the first one):

In [276]:
stepSize ← 3 1
{⊂⍵}⌺(2 2⍴ws,stepSize)⊢mat

The step size can be increased arbitrarily, even if further increases do not modify the output:

In [277]:
{⊂⍵}⌺(2 2⍴ws,123409 1)⊢mat

A step size of 123409 along the first axis means that we keep one out of every 123409 rows.
Because there are only 3 rows in the complete result, we keep the very first one, and that is it.

(Operators-Image-Processing-with-Stencil)=
### Image Processing with Stencil

The operator _stencil_ is very useful in domains like image processing or neural networks.
A simple application example is the usage of the operator _stencil_ to blur images.

{numref}`fig-Image` is an image we will blur:

(fig-Image)=
```{figure} ../res/Image.png
---
name: Image
---
A screenshot of the Dyalog website in late 2022.
```

{numref}`fig-Image_Blurred` is the blurred version:

(fig-Image_Blurred)=
```{figure} ../res/Image_Blurred.png
---
name: Image_Blurred
---
A blurred screenshot of the Dyalog website in late 2022.
```

The main piece of code that blurs the image is this:

```APL
Blur ← {(+⌿,⍵)÷49}⌺7 7
newImage ← Blur⍤2⊢image
```

The function `Blur` goes over sub-matrices of shape 7 by 7 and then computes the average value of each 7 by 7 sub-matrix as the new value that will go in a given position.
This is one way to achieve a simple blurring effect.
Then, the expression that computes the new image applies the function `Blur` to each 2-cell of the array `image`, because `image` is actually a cuboid with three layers, where each layer represents a colour channel in the RGB colour space.

(If you are not familiar with the RGB colour space, you can think of it as saying that a colour can be determined by its amount of **r**ed, **g**reen, and **b**lue.
Thus, in our code, we need to blur the red, green, and blue, layers, which is why we use `Blur⍤2`.)

(Operators-Power)=
## Power

_Power_ is a dyadic operator represented by the glyph `⍣` that you can type with <kbd>APL</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>, which is easy to remember because P is the initial letter of _power_ and because the glyph `⍣` is just the `*` with a diaeresis on top.
The operator _power_ produces a derived function that is either monadic, dyadic, or ambivalent, depending on the function used as the left operand.
Again, depending on the left operand, the derived function may return a result or not.

The general syntax is `{result} ← {left} F⍣n ⊢ right`, if the right operand is an integer, or `{result} ← {left} F⍣C ⊢ right`, if the right operand is a function.
The two usages are explained next.

(Operators-Power-n-Times)=
### Power `n` Times

If the right operand `n` is an integer scalar, the left operand function `F` is applied `n` times to the argument `right` (if the derived function is used monadically) or to `left` and `right` (if the derived function is used dyadically).

Like with some other operators we have seen already, the right operand `n` must be separated from the right argument, either by parenthesising the whole derived function or by using a _right tack_ between the right operand and the right argument.

Imagine we have a little matrix `mat`:

In [278]:
mat

And we write a function to spin it a quarter of a turn:

In [279]:
Spin ← {⊖⍉ ⍵}

In [280]:
Spin mat

In [281]:
Spin Spin mat

Of course, after 4 executions, the matrix would return to its original position.

We can spin the matrix any number of times using the operator _power_ instead of writing `Spin` repeatedly:

In [282]:
Spin Spin mat

In [283]:
Spin⍣2⊢mat

In [284]:
Spin Spin Spin Spin Spin Spin Spin Spin Spin mat

In [285]:
Spin⍣9⊢mat

The example above shows that 9 spins are equivalent to a single spin.

The operator _power_ can also give us a way of calculating a Fibonacci series:

In [286]:
Fibo ← {⍵,+/¯2↑⍵}
Fibo⍣10⊢1

(Operators-Conditional-Execution)=
### Conditional Execution

As a special case, when `n` is a Boolean value, the left operand function is applied (1) or not applied (0).
It simulates the conditional execution of the function.

In the example below, the right operand to _power_ is 1, so we round down our values:

In [287]:
⌊⍣1 ⊢ 23.73 42.25

In the next example, the right operand to _power_ is 0, so we do not round down:

In [288]:
⌊⍣0 ⊢ 23.73 42.25

For example, a function has been written in such a way that it works only on nested vectors, but sometimes its right argument `v` is a simple vector (not nested) or even a scalar.
So, one must _ravel_ `v` (if it is a scalar), _enclose_ it, then _ravel_ again to produce a vector, or do absolutely nothing if `v` is already a nested vector.
The following expression will perform the necessary transformations: `({,⊂,⍵} ⍣ (1=≡,v)) v`.

In [289]:
⎕← v ← 'nested' 'vector'

In this case, `v` is already a nested vector, so the expression above shouldn't do anything to `v`:

In [290]:
({,⊂,⍵} ⍣ (1=≡,v)) v

In the next example, we define `v` to be a simple vector, which means the expression should nest it:

In [291]:
⎕← v ← 'simple vector'

In [292]:
⎕← newV ← ({,⊂,⍵} ⍣ (1=≡,v)) v

In [293]:
⍴newV

Whether one prefers to use the operator _power_ to write such a compact conditional expression, or to use a traditional control structure (`:If ... :EndIf`) is mostly a matter of taste.
Some may find the former easier to write and read than the latter, while others may disagree.

The version with the operator _power_ has the advantage that it works inside a _dfn_.

(Operators-Left-Argument)=
### Left Argument

If a left argument `left` is provided to the derived function, it is bound as the left argument to the left operand `F` in `left F⍣n ⊢ right`.
It is the same thing if, instead of an integer right operand, we have a function right operand in `left F⍣C right`.

So, the expression

In [294]:
3 ×⍣4⊢ 2

is the same as

In [295]:
  3× 3× 3× 3× 2
⍝ 1  2  3  4

and not

In [296]:
3 ×2 ×2 ×2 ×2
⍝ 1  2  3  4

(Operators-Inverse-Function)=
### Inverse Function

If the right operand `n` is a **negative** integer, the function executed by the operator _power_ is not `F`, but its _inverse_ function – provided such an inverse function exists and APL knows about it.
If the inverse function to `F` is not known to APL, a `DOMAIN ERROR` will be reported.
In particular, APL is not able to find the _inversion function_ of user-defined function, and some primitive functions have no _inverse function_.

If `n` is negative, the _inverse function_ is applied `|n` times.

The function `F` may be an appropriate primitive function or an expression consisting of such primitive functions combined with primitive operators among _each_ `¨`, _outer product_ `∘.`, _axis_ `[n]`, _scan_ `\`, and _power_ `⍣`.
Later in {numref}`Operators-Inverting-Functions-with-the-Operator-Power` you will see that there are some other operators that you can also use and that the operator _power_ will know how to invert.

As an example, let us compute the inverse of _plus scan_:

In [297]:
(+\ ⍣ ¯1) 3 4 9 15 19

We can confirm this result:

In [298]:
+\ 3 1 5 6 4

The _inverse function_ can also accept a left argument:

In [299]:
left ← 2 5 3
⎕← right ← 3 4⍴10 4 14 8 25 10 35 20 15 6 21 12

In [300]:
left (∘.× ⍣ ¯1) right

In this case, the _inverse function_ computed the vector that you would need to combine with the vector `left` to produce the matrix `right`:

In [301]:
right ≡ left ∘.× 5 2 7 4

(Operators-Fixed-Point-and-User-Defined-Operators)=
### Fixed Point and User-Defined Operators

Here are two additional features of the operator _power_:

 1. in its second form, the operator _power_ has two function operands: `{left} F⍣C right`; and
 2. some common patterns in user-defined operators make use of _power_.

These two types of use require an advanced knowledge of APL and of _user-defined operators_.
They will not be presented now, but {numref}`Operators-Advanced-Uses-of-the-Operator-Power` covers _power_ with two function operands and {numref}`Operators-Under` covers one such common pattern.
Have a look at it when you feel ready.

(Operators-Spawn)=
## Spawn

(Operators-Main-Features)=
### Main Features

The monadic operator _spawn_ is represented by an ampersand `&` and your regular keyboard should be able to type it already.
It executes a function asynchronously from the main flow of execution in a separate sequence of instructions known as a _thread_.

If the main flow of execution and the function executing in the separate thread are both using the CPU heavily, nothing is gained by starting a separate thread.
On the contrary, the two threads will be competing for the same resource – the CPU, which requires some overhead.
But if one of the threads involves waiting time in which it cannot make use of the CPU, the other thread may use the CPU, which otherwise would have been idle.
In such cases, a considerable improvement of the application's perceived performance may be observed.

There are many situations in which a thread may be waiting and not be able to make good use of the CPU: it may be waiting for user input, a file operation, a response from a web client or server, or a response from a database manager, to give just a few examples.

_Spawn_ is itself monadic, but its derived function is monadic, dyadic, or ambivalent, according to the definition of its left function operand.
This function (and hence the derived function) may not be niladic.

```{admonition} Remark 
:class: tip
If you are reading this book in its interactive format, we suggest you try the examples with the operator _spawn_ in your local interpreter.
That is because the operator _spawn_ interacts in inconvenient ways with the notebook software.
```

_Spawn_ returns as a _shy result_ the number of the thread in which the task is executed.

The main execution flow is executing in thread number 0, so the first time one launches a new thread, it is executed in thread number 1.
Let us execute `⍳5` in a separate thread:

```APL
      ⎕← ⍳& 5
1
1 2 3 4 5
```

In the example above, the _quad_ forces the shy result (the new thread number) to be displayed, which is 1 because this is the first thread we start.
Then, the function result is displayed.

```{admonition} Remark 
:class: tip
It may happen that you run the expression `⎕← ⍳& 5` and the output is the same as the one above, but with the two lines swapped.
If the left operand of _spawn_ is a simple/small expression, it may finish executing before the _quad_ gets a chance to print the thread number.
```

Once a thread number has been used, it will not be used again in this session: the thread number will be incremented every time _spawn_ is used:

```APL
      ⎕← ÷& 2 5 10
2
0.5 0.2 0.1
```

As we can see, the second time we use _spawn_, the thread number was incremented to 2.

In these examples, the derived function was monadic; let us now use a dyadic function operand, and try to execute `2 3 7 × 4 6 5` in a separate thread:

```APL
      r ← 2 3 7 ×& 4 6 5
8 18 35
```

Beware of the previous example!
You may think that `r` contains the result of the function call, but it does not.
It contains the thread number:

```APL
      r
3
```

If you think about it, it should not come as a surprise that the result of starting a new thread is not the result of the function call.
If that had been the case, the main execution thread would have had to stop and wait until the execution of the function had completed – and we would not have had any parallel execution at all!

So, if we cannot get hold of the result of the function call when starting it using the operator _spawn_, how can we get hold of it later, when we assume that the function has completed execution?

The answer is the monadic _system function_ `⎕TSYNC` (_thread synchronization_).
It takes an array of thread numbers as its argument.
It then causes the thread in which it is executing to stop and wait until all the threads listed in the argument have completed execution.
Then, it returns an array of the same shape as the right argument, each item containing the result of the function call executed in the corresponding thread.

Let us build a simple example using the system function `⎕DL` (_delay_), which simply stops execution for approximately a specified number of seconds.
`⎕DL` returns, as a result, the exact length of the delay.

```APL
      ⎕ ← tn ← ⎕DL& 10
4
      ⎕ ← ⎕TSYNC tn
10.045
```

We start a new thread that will just waste 10 seconds and its thread number is saved in the variable `tn`, which we then print and see it is 4.
The thread number is displayed immediately.
Then, we wait approximately 10 seconds, and then we print the result that is returned by `⎕DL`.

It will never really make sense to use primitive functions with _spawn_, as this will only slow the system down.
In practice, _spawn_ is always used to start user-defined functions in situations where you don't mind that your main thread slows down a little while a job is done in the background.
For example, you might start a function which prepares a print job and let it run in the background.
Your application will possibly run more slowly until the print job is completed, but you can avoid having to make your user wait until the print job is finished.
If the user is typing in data for the next job, the slowdown may not even be noticeable.

Programming using multiple threads is complex and requires great care.
In particular, you have to be careful about what happens to global or semi-global variables that can be seen by more than one thread.
Dyalog contains several mechanisms for controlling and synchronising the execution in threads.
The operator _spawn_ and `⎕TSYNC` are just the two most basic ones.
We will not go into further detail about the others here; please refer to the Dyalog help file if you are interested in learning more about using multiple threads in Dyalog.

(Operators-Special-Syntax)=
### Special Syntax

Suppose we have three functions:

 - `DyaFun` is dyadic;
 - `MonaFun` is monadic; and
 - `NilFun` is niladic.

`47 DyaFun& 60` will execute `DyaFun` in a separate thread.
The derived function is dyadic: `47 (DyaFun&) 60`.

`MonaFun& 33` will execute `MonaFun` in a separate thread.
The derived function is monadic: `(MonaFun&) 33`.

`NilaFun&` **will not work**; it will cause a `VALUE ERROR`!
Why?

The reason is that the APL syntax does not allow operators to be used with niladic functions, although there is really no specific reason why it should not be possible to run a niladic function in a separate thread.
There are workarounds, though:

 - `⍎& 'NilaFunc'` – the operand of _spawn_ is the function _execute_ (`⍎`) and the argument of the _derived function_ is the name of the function we would like to execute: `'NilaFunc'`. Finally, this will launch `⍎'NilaFunc'` in a new thread, and it works as expected!
 - `{NilaFunc}& 0` – here, `NilaFunc` is embedded in a dfn, which is always ambivalent. A dummy right argument is provided, but ignored (any value will do).

_Spawn_ can be used in conjunction with _each_ (`¨`) to launch several parallel threads in one expression.

(Operators-User-Defined-Operators)=
## User-Defined Operators

As we have seen, APL offers a set of primitive _functions_, and you can write your own _user-defined functions_.
Likewise for _operators_: Dyalog APL has a large set of primitive operators, but you can write your own _user-defined operators_.

As for functions, there are two types of _user-defined operators_, and we will cover both of them next.

(Operators-Dops)=
### Dops

Dops are just like dfns with a few extra conventions:

 - `⍺⍺` represents the left operand of the operator;
 - `⍵⍵` represents the right operand of the operator;
 - `⍺` is the left argument of the _derived function_; and
 - `⍵` is the right argument of the _derived function_.

Using these conventions, suppose that we want to simulate _inner product_.
We could write:

In [302]:
_InPro_ ← {⍺ ⍺⍺.⍵⍵ ⍵}

To see if it works, we can just check that we obtain the same results as with the primitive _inner product_:

In [303]:
(percent +_InPro_× invest) ≡ percent +.× invest

In the previous example, `⍺⍺` was set to `+` and `⍵⍵` was set to `×`.

In [304]:
(words ∧_InPro_= 'COLONEL') ≡ words ∧.= 'COLONEL'

Throughout this book we will use the convention that _user-defined operators_ have leading underscore if they are monadic, or a leading and trailing underscore if they are dyadic.
This will help distinguish operators from functions.
Recall that this is just a convention and you are not forced to follow it.

```{admonition} Remark 
:class: tip
A dfn becomes a dop if it mentions either `⍺⍺` or `⍵⍵` explicitly.
For example, `{⍺⍺ ⍵}` is a dop.
The code `{{⍺⍺ ⍵} ⍵}` _might_ look like a dop, but it is not.
The outer `{...}` is a dfn because it does not mention the names `⍺⍺` or `⍵⍵`.
```

(Operators-Traditional-Operators)=
### Traditional Operators

Traditional operators, often referred to as tradops, have a syntax similar to that of tradfns.
The names of the operands must be parenthesised together with the name of the operator.
The name(s) of the argument(s) to the derived function are specified on either side of the parentheses.

With this in mind, here are the possible header structures for a dyadic tradop:

| Syntax | Valence of the derived function |
| :- | :- |
| &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`(F _Op_ G) right` | Monadic |
| &nbsp;&nbsp;`left  (F _Op_ G) right` | Dyadic |
| `{left} (F _Op_ G) right` | Ambivalent |

Similarly, here are the possible header structures for a **monadic** tradop:

| Syntax | Valence of the derived function |
| :- | :- |
| &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`(F _Op) right` | Monadic |
| &nbsp;&nbsp;`left  (F _Op) right` | Dyadic |
| `{left} (F _Op) right` | Ambivalent |

Recall that neither an operator nor its derived function can be niladic.

If we wanted to simulate _inner product_ again, but this time with a tradop, it would look something like this:

In [305]:
∇ r ← left (F _InPro_ G) right
    r ← left F.G right
∇

In [306]:
(percent +_InPro_× invest) ≡ percent +.× invest

(Operators-Some-Basic-User-Defined-Operators)=
### Some Basic User-Defined Operators

Just to experiment a little, let us define a dyadic operator with a dyadic derived function:

In [307]:
_Op_ ← {(⍺ ⍺⍺ ⍺) ⍵⍵ (⍵ ⍺⍺ ⍵)}

In [308]:
5 ×_Op_+ 8  ⍝ ←→ (5×5) + (8×8)

In [309]:
5 +_Op_× 8  ⍝ ←→ (5+5) × (8+8)

You probably remember that we used a _multiply-scan_ to calculate a vector of inflation rates, which we then used to calculate the future values of investments given as current values (see {numref}`Operators-Inflate-Values`).
We could just as well have used the rates to calculate the current values if we knew the future values.
So, why not create an operator that can be used to transform future values into current values, or the inverse.
Let us name it `_InDef` (for Inflate / Deflate).

The derived function arguments will be the inflation rates (left) and the investment values (right):

In [310]:
∇ values ← rates (action _InDef) values
    values ← values action ×\1+rates÷100
∇

Example values:

In [311]:
inv

In [312]:
inf

We can use it to calculate the future values using multiplication:

In [313]:
2⍕ inf ×_InDef inv

Using division, we can do the inverse:

In [314]:
2⍕ inf ÷_InDef 3200 4300 3800 2500 2500

We can also go forward and back:

In [315]:
inf ÷_InDef inf ×_InDef inv

[The "Specialist's Section"](#Under) describes an interesting _user-defined operator_.

(Operators-More-Exercises)=
## More Exercises

```{exercise}
:label: trim-long-subvectors
Write a function that receives a vector of vectors and returns the same vector of vectors, but all the subvectors that had a length of four or more were replaced by their first three elements.
How would you have to implement this function if you wanted to use the operator _at_?
```

In [316]:
TrimLong ← {({3↑¨⍵}@({3<≢⍵}¨))⍵}

In [317]:
⍳¨⍳5

In [318]:
TrimLong ⍳¨⍳5

```{exercise}
:label: rank
The cuboid `prod`, shown below, contains production data for 5 years of production, on 2 assembly lines, across the 12 months of the year.
To each _major cell_ of `prod`, add information about the total production in each assembly line (across the 12 months) and for each month (across the 2 assembly lines).
Try to solve this problem without using _axis_.
```

In [319]:
⎕RL ← 73
⎕← prod ← ?5 2 12⍴50

In [320]:
Totalise ← {m,⍤¯1+/⍤2⊢m←⍵⍪⍤¯1+⌿⍤2⊢⍵}

In [321]:
Totalise prod

```{exercise}
:label: cross-count-key
Recall the vectors `status` and `graduated`:

 1. `status` – a character vector specifying a person's marital status (Single, Married, Divorced, Widow, Unknown); and
 2. `graduated` – a character vector specifying if the person has graduated or not (Yes/No).

Write a function to count how many people are in each category, but make use of the operator _key_.
```

In [322]:
]dinput
CrossCountKey ← {
    statusOrder ← 'SMDWU'
    base ← ('YN',⍺) {{¯1+≢⍵}⌸ statusOrder,1↓⍵}⌸ '  ',⍵
    base ,← +/base
    base ⍪← +⌿base
    (' ',statusOrder,⊂'Total')⍪('YN',⊂'Total'),base
}

In [323]:
⎕RL ← 73
⎕← 10↑status ← 'SMDWU'[?300⍴5]

In [324]:
⎕RL ← 73
⎕← 10↑graduated ← 'YN'[?300⍴2]

In [325]:
graduated CrossCountKey status

```{exercise}
:label: house-market-sales
The matrix `data` below contains house sales data for a real estate company.
The data pertains to the years 2016, 2017, and 2018, across the 4 quarters of each year, for three locations: Lisbon, Madrid, and Berlin.
Each row in the matrix contains the year, the quarter, the location (3 letter code), and the value of a sale a real estate company made, in thousands of euros.

Answer these questions:

 - What was the most expensive house sold in each city, per year?
 - How many sales did the real estate company make per year and per quarter?
 - What was the volume of sales per year in millions of euros? What about per year and per location?

To help you verify your answers, here are partial answers:

 - In 2017, the most expensive houses in thousands of euros, were 353 in Lisbon, 396 in Berlin, and 400 in Madrid.
 - In 2017, the real estate company made 5, 8, 4, and 13, sales per quarter, respectively in quarters 1 through 4.
 - The volume of sales, in millions of euros, was 8.605 in 2016.
 - The volume of sales, in millions of euros, in Berlin was 3.838, 3.643, and 3.613, respectively in 2016, 2017, and 2018.
```

In [326]:
⎕RL ← 73
data ← ⍉↑(2015+?103⍴3)(?103⍴4)(('LIS' 'MAD' 'BER')[?103⍴3])(?100+103⍴300)
header ← 'Year' 'Quarter' 'Location' 'Sale'
header⍪10↑data

In [327]:
'Most expensive house' 2016 2017 2018⍪data[;3] {⍺, (2016,2017,2018,⍵[;1]) {⌈⌿,⍵[;4]}⌸ 0⍪0⍪0⍪⍵}⌸data

In [328]:
'Year' 'Q1' 'Q2' 'Q3' 'Q4'⍪(2016,2017,2018,data[;1]) {⍺,{¯1+≢⍵}⌸ (⍳4),1↓⍵[;2]}⌸ 0⍪0⍪0⍪data

In [329]:
data[;1] {⍺, 1000÷⍨+⌿⍵}⌸ data[;4]

In [330]:
data[;1] {⍺, ⍵[;1] {⍺,1000÷⍨+⌿⍵}⌸ ⍵[;2]}⌸ data[;3 4]

```{exercise}
:label: minesweeper
[Minesweeper](https://en.wikipedia.org/wiki/Minesweeper_(video_game)) is a logic game in which the player has to pinpoint the location of mines in a rectangular grid.
To help the player, each square that is not a mine gets a clue: an integer from 0 to 8 that identifies how many mines can be found in the 3 by 3 region centred around the clue square.

Write a function `MakeClues` that takes a rectangular Boolean grid indicating the positions of the mines and returns the rectangular grid with the clues superimposed on the grid with mines.
```

In [331]:
]dinput
MakeClues ← {
    clues ← {+⌿'*'=,⍵}⌺3 3⊢⍵
    notMines ← ⍸'*'≠⍵
    clues[notMines]@notMines⊢⍵
}

In [332]:
⎕← mines ← 3 4⍴'⎕*⎕⎕**⎕⎕*⎕⎕*'

In [333]:
MakeClues mines

```{exercise}
:label: stencil-n-wise-reduction
Implement _n-wise reduction_ on vectors as a user-defined operator, in terms of _stencil_ and regular _reductions_.
```

In [334]:
_NWiseReduce ← {F ← ⍺⍺ ⋄ p ← ⌊(⍺-1)÷2 ⋄ (-p)↓p↓{F/⍵}⌺⍺⊢⍵}

In [335]:
2 +_NWiseReduce ⍳10

In [336]:
4 ×_NWiseReduce ⍳5

```{exercise}
:label: power-if
Implement a dyadic operator called `_If_` that defines a monadic derived function.
In other words, the signature of `_If_` is `F _If_ G right`.
`G` must be a monadic Boolean function.
If `G right` gives 1, then we return `F right`, otherwise we return just `right`.
Try to implement `_If_` in terms of the operator _power_.
```

For an extra challenge, after solving the exercise above, try to make the derived function `F _If_ G` ambivalent:

 - if there is only the right argument `F _If_ G right` then we get `F right` if `G right` is 1 otherwise we get just `right`; and
 - if there is also the left argument `left F _If_ G right`, then we get `left F right` if `left G right` is 1 otherwise we get just `right`.

Beware that this is not an easy challenge, but the solution you will be shown involves a pattern that is worth knowing.

In [337]:
_If_ ← {⍺ ← ⊢ ⋄ ⍺ (⍺⍺⍣(⍺ ⍵⍵ ⍵)) ⍵}

In [338]:
TimesTen ← {10×⍵}
IsSmall ← {⍵<10}

In [339]:
TimesTen _If_ IsSmall 5

In [340]:
TimesTen _If_ IsSmall 12

(Operators-The-Specialists-Section)=
## The Specialist's Section

<br />
<center><i>Each chapter is followed by a "Specialist's Section" like this one. This section is dedicated to skilled APLers who wish to improve their knowledge.</i>

You will find here rare or complex usages of the concepts presented in this chapter, or discover extended explanations which need the knowledge of some symbols that will be seen much further in the book.

<b>If you are exploring APL for the first time, skip this section and go to the next chapter.</b></center>

(Operators-Reduction-Applied-to-Empty-Vectors)=
### Reduction Applied to Empty Vectors

(Operators-Identities)=
#### Identities

Suppose we have two numeric vectors `a` and `b`, for example:

In [341]:
a ← 2 4 1
b ← 7 3 6

You can see that

In [342]:
+/a,b

is equal to

In [343]:
+/a,+/b

Similarly,

In [344]:
×/a,b

is equal to

In [345]:
×/a,×/b

In general, for any two vectors `a`, `b`, and for any valid dyadic function `F`, the expressions `F/a,b` and `F/a,F/b` give the same result.
To see why this is the case, recall that the expression `F/a,b` reduces all the elements in the vector `a,b` from right to left, which means that we start by reducing the values in `b` and then we move on to the values in `a`.
So, the expression `F/a,F/b` is equivalent to `F/a,b` because `F/b` represents a partial result in the computation of `F/a,b`.

If the vector `b` is the empty vector, then we see that `a,b` is the same as `a`, which means that `F/a ←→ F/a,b ←→ F/a,F/b`.
We can use this equivalence to determine what `F/b` should give when `b` is the empty vector, because `F/a ←→ F/a,F/b` shows that `F/b` should be a value that can be appended to `a` and that will **not** change the result of the reduction.

For example, in _plus-reductions_, we see that `+/⍬` must be 0 because 0 is the _identity element_ of addition.
In other words, 0 is the element that does not change the result of an addition:

In [346]:
+/⍬

In [347]:
+/a,+/⍬

In [348]:
+/a,0

Similarly, in _times-reductions_, we see that `×/⍬` must be 1 because 1 is the _identity element_ of multiplication.
In other words, 1 is the number that does not change the result of a multiplication:

In [349]:
×/⍬

In [350]:
×/a,×/⍬

In [351]:
×/a

(Operators-Rule)=
#### Rule

The reduction of an empty vector by any dyadic **primitive** function `F` returns the _identity element_ of that function `F` (0 for _addition_, 1 for _multiplication_, etc...).
If `F` has no _identity element_, a `DOMAIN ERROR` is issued.

(Operators-Examples)=
#### Examples

Some _identity elements_ are obvious:

In [352]:
+/⍬

In [353]:
×/⍬

Some others may need a little explanation:

In [354]:
⌊/⍬

The _identity element_ of the function _minimum_ is the largest possible value that APL can represent in your computer, because any other number compared to it will be smaller.

A similar reasoning explains the _identity element_ of the function _maximum_:

In [355]:
⌊/⍬

(Operators-Non-Commutative-Functions)=
#### Non-Commutative Functions

The examples we have seen above involved _commutative_ functions.
Things become more complicated with _non-commutative_ functions because, in general, you will get different results if you swap the arguments to a non-commutative function.
Thus, a value that works as an _identity element_ if used as the left argument cannot be expected to be an _identity element_ when used as a right argument.

So, a non-commutative function may have

 - an identity value that works as left argument (a left identity element);
 - an identity value that works as right argument (a right identity element); or
 - no identity at all.

Here are some examples:

In [356]:
*/⍬

The right identity element of the function _power_ is 1 because any number raised to the power of 1 gives the same number, but the function _power_ has no left identity element.

In [357]:
⌽/⍬

The function _rotate_ has the left identity element 0 because a rotation of 0 leaves any array unchanged, but the function _rotate_ has no right identity element.

In [358]:
//⍬

The function _compress_ has the left identity element 1 because an array compressed with 1 is preserved, but the function _compress_ does not have a right identity element.

(Operators-Application-to-n-Wise-Reduction)=
#### Application to n-Wise Reduction

The properties described above explain the results returned by _n-wise reduction_ when its left argument is 0.

Let us just explore how it processes vectors: we saw earlier that the result size of `n F/ vector` is `(1+≢vector)-n`.
If `n` is 0, the result size is `1+≢vector`.
And, if `n` is 0, the slices are all empty.
Hence, the result is composed of _identity elements_ of the function in question (if such an _identity element_ exists, of course):

In [359]:
vec ← 3 2 6 1 8

In [360]:
0 +/ vec

In [361]:
0 ×/ vec

(Operators-Index-Origin-and-Axis-Operator)=
### Index Origin and Axis Operator

Changing _index origin_ has an impact on the use of _axis_.
For example, with the default value `⎕IO ← 1`:

In [362]:
a ,[1.5] b

If we change the _index origin_, we have to adjust the operand to _axis_ accordingly:

In [363]:
⎕IO ← 0
a ,[.5] b

In [364]:
a ,[¯.5] b

In [365]:
⎕IO ← 1
a ,[.5] b

For this reason, when an operation applies to the first or the last dimension of an array, it is recommended to use the special symbols rather than specifying an axis, as the special symbols work independently of `⎕IO`.

To apply the function along the last dimension (the default), use `/`, `,`, `⌽`, `\`.
To apply the function along the first dimension, use `⌿`, `⍪`, `⊖`, `⍀`.

We had already mentioned in {numref}`Working-on-Data-Shape-More-About-Laminate` that a fractional _axis_ used with _laminate_, _ravel with axis_, or _mix_, sometimes has to be negative when `⎕IO` is set to zero.
Above, we saw another example of that.

(Operators-Rank-Outer-Products)=
### Rank Outer Products

The operator _rank_ can be used in an interesting pattern to implement an _outer product_ on arbitrary cells.
The operator _outer product_ combines all the 0-cells of the left and right arguments:

In [471]:
(⍳2) ∘.{⍺ ⍵} 3 4⍴⎕A

By using the operator _rank_ in the appropriate way, we can create an _outer product_ that operates on the j-cells of the left argument and the k-cells of the right argument.
For example let us combine all rows of this matrix:

In [475]:
⎕← mat ← 2 4⍴⎕A

With all the sub-matrices of this cuboid:

In [476]:
⎕← cuboid ← 3 4 5⍴⍳60

So, we want to apply `F` to all combinations of 1-cells of the array `mat` and 2-cells of the array `cuboid`.
To implement this _outer product_ pattern, we use the operator _rank_ once on `F` to apply `F` to all 2-cells of the right argument while leaving the left argument intact:

In [483]:
mat {⍺ ⍵}⍤99 2⊢ cuboid

Then, we use the operator _rank_ once more to apply the function `F⍤99 2` to the 1-cells of the left argument while leaving the right argument intact:

In [484]:
mat {⍺ ⍵}⍤99 2⍤1 99⊢ cuboid

The 99 in the operand of _rank_ is to ensure that we capture the whole argument, regardless of the argument we end up using.
If we know beforehand what are the ranks of the arguments, we do not need to use the value 99.

To conclude, if you want to apply the function `F` to all combinations of j-cells of the left argument with k-cells of the right argument, use `F⍤99 k⍤j 99`.

A useful example of this pattern is `F⍤99 ¯1⍤¯1 99`, which is the _outer product_ between _major cells_ of the left and right arguments.

(Operators-The-Full-Rank-Specification)=
### The Full Rank Specification

The full specification of the operator _rank_ says that the right operand can be an integer vector with up to three elements.
In its most general form, we have `F⍤p q r`:

 - `p` specifies the rank of the argument cells when `F` is applied monadically;
 - `q` specifies the rank of the left argument cells when `F` is applied dyadically; and
 - `r` specifies the rank of the right argument cells when `F` is applied dyadically.

The form `F⍤r` is equivalent to `F⍤r r r` and the form `F⍤q r` is equivalent to `F⍤r q r`.

(Operators-Optimised-Left-Operands-for-Stencil)=
### Optimised Left Operands for Stencil

The operator _stencil_ recognises certain left operand functions and runs specialised code in those cases, resulting in much faster execution times for those cases.

The simplest special left operand is `{⍵}` and we show the speed up it gets from the special code recognition.
To do this comparison, we need to "break" the special code recognition without adding code that slows down the timing comparisons.
Typically, adding the _identity_ is enough, but `{⊢⍵}` is also special-cased, so we need to add two _right tacks_:

In [487]:
mat ← ?100 200⍴0
]runtime -c "{⍵}⌺3 5⊢mat" "{⊢⍵}⌺3 5⊢mat" "{⊢⊢⍵}⌺3 5⊢mat"

The special left operands are as follows:

 - `{⍵}`, `{⊢⍵}`, `{,⍵}`, `{⊂⍵}`;
 - `{+/,⍵}`, `{∧/,⍵}`, `{∨/,⍵}`, `{=/,⍵}`, `{≠/,⍵}`;
 - `{  +/,A×⍵}`, `{  +/⍪A×⍤2⊢⍵}`; and
 - `{C<+/,A×⍵}`, `{C<+/⍪A×⍤2⊢⍵}`.

In the above, we have that:

 - `C` is a single number or a variable whose value is a single number;
 - `A` is a variable whose value is a rank-2 or rank-3 array;
 - the comparison can be any of `< ≤ ≥ > = ≠`; and
 - the operator is assumed to be applied with odd window size, movement 1, and matrix argument.

(Operators-Inverting-Functions-with-the-Operator-Power)=
### Inverting Functions with the Operator Power

In {numref}`Operators-Inverse-Function` we learned that the operator _power_ can invert functions that are primitive functions modified with primitive operators.
We must note that the operator _power_ can also invert functions that contain the operators _beside_ `∘`, _atop_ `⍤`, _over_ `⍥`, and _commute_ `⍨`.

It is also worth noting that the operator _power_ can invert some tacit functions, provided the primitives that make up the tacit function can be inverted.
This is not a sufficient condition, but it is necessary.

Here is an example with a short numerical tacit function:

In [493]:
2 (*+×) 5

In [494]:
2 (*+×)⍣¯1⊢ 42

(Operators-Under)=
### Under

In mathematics, physics, and other domains, there are many cases in which one wants to apply a given transformation `F`, but first some pre-processing must be applied, then one can apply `F`, and then the pre-processing must be undone.

For example, in electricity, the effective resistance of n resistors connected in parallel is the inverse of the sum of the inverses of the individual resistors' resistances.
By chance, the function _reciprocal_ `÷` is its own inverse.

If the resistance of 5 resistors connected in parallel are given in Ohms in the vector below:

In [499]:
resistances ← 2 50 7 4 10

Then, the effective resistance can be calculated easily as:

In [511]:
Resistance ← {÷+/÷⍵}

In [512]:
Resistance resistances

In the example above, the pre-processing that had to be done and then undone was computing the reciprocals of the numbers that we wanted to sum.

An implementation of the _bitwise right shift_ operation exhibits this pattern again.
To implement _bitwise right shift_ we must take the integer we want to shift, convert it to binary, shift its binary representation to the right, and then convert back to decimal.

Here is a possible implementation:

In [535]:
RightShift ← {2⊥(⍺⍴0),⍨2⊥⍣¯1⊢⍵}

In [536]:
1 RightShift 2

In [537]:
2 RightShift 2

In [538]:
3 RightShift 124

An implementation of the _bitwise shift left_ operation would be very similar:

In [539]:
LeftShift ← {2⊥(-⍺)↓2⊥⍣¯1⊢⍵}

In [540]:
1 LeftShift 4

In [541]:
2 LeftShift 4

In [542]:
3 LeftShift 123

The pattern of doing a pre-processing step `P`, applying a transformation `F`, and then undoing the pre-processing by applying `P⍣¯1` is commonly implemented as the operator _under_:

In [552]:
_Under_ ← {⍺ ← ⊢ ⋄ ⍵⍵⍣¯1⊢⍺ ⍺⍺ ⍵⍵ ⍵}

If we make use of the operator _under_, we can implement the functions `Resistance`, `RightShift`, and `LeftShift`, in terms of it:

In [553]:
Resistance ← +/_Under_÷
Resistance resistances

In [558]:
RightShift ← {⍵,⍺⍴0}_Under_(2∘⊥⍣¯1)
3 RightShift 124

In [559]:
LeftShift ← {(-⍺)↓⍵}_Under_(2∘⊥⍣¯1)
3 LeftShift 123

(Operators-The-Result-of-an-Inverse-Function)=
### The Result of an Inverse Function

As shown in {numref}`Operators-Inverse-Function`, the derived function returned by the operator _power_ is the _inverse_ of its left operand when the right operand is negative.

Therefore, the following identity is usually true for a function `F` for which an inverse function exists:

<center><code>right ≡ {left} F⍣¯1⊢ left F right</code></center>

For example:

In [586]:
2 ≡ ÷⍣¯1⊢ ÷2

However, where several possible inverses exist, the "simplest" is chosen.
For example:

In [587]:
2⊥1 1

Notice how prepending a 0 does not change the result:

In [588]:
2⊥0 1 1

However, the inverse does not add the zero:

In [589]:
2 ⊥⍣¯1⊢ 3

The identity we showed holds true:

In [591]:
1 1 ≡ 2 ⊥⍣¯1 ⊢ 2⊥1 1

But not if we include the extra zero, because the inverse function will return a "simpler" inverse:

In [592]:
0 1 1 ≡ 2 ⊥⍣¯1 ⊢ 2⊥0 1 1

To conclude, notice that `2⊤` is different from `2⊥⍣¯1`:

In [593]:
2⊤3

This shows that the use of _inverse decode_ rather than _encode_ allows you to let the system decide how many digits are needed to do the full base conversion.

(Operators-Advanced-Uses-of-the-Operator-Power)=
### Advanced Uses of the Operator Power

In its second form, the operator _power_ has two operands: `{left} F⍤C ⊢ right`.
The right operand `C` must be a dyadic function that returns a Boolean scalar.
The left operand `F` is applied repeatedly like this: `v_ ← {left} F v` until the condition `v_ C v` evaluates to 1.
To start off, `v` is set to `right` and, after reach iteration, `v` is updated with `v_`.
Thus, `F⍣C` computes a series of values in which the left argument to `F` is always `left`, if present, and the right argument to `F` starts off as `right` and then gets successively updated.

To demonstrate this, let us use this extremely silly function:

In [581]:
⎕RL ← 42
Silly ← {⎕← '⍺: ',⍺,'⍵: ',⍵ ⋄ ⊢⎕←?⍵+⍺}
10 Silly⍣> 20

The output above shows that, in all iterations, the left argument was always 10.
Then, we see that the right argument started off as 20 and then it got successively updated as the result of the previous iteration, so it went from 20 to 11, and then to 3.
When the right argument was 3, the result was 9 and then `9 > 3` evaluated to 1.

If the condition never evaluates to 1, the derived function will continue to execute until it is stopped by a _strong interrupt_.

When `C` is `=` or `≡`, the result is called the _fixed point_ of the function `F`.

For all the many mathematical iterative calculations that converge towards a final limit, this use of the operator _power_ is certainly something you should consider.

Here is the example of the golden ratio, a mathematical number that can be approximated by the following expression:

In [582]:
1 +∘÷⍣= 1

The golden ration can be defined as the result of the expression that follows, assuming it could have an infinite number of terms:

In [585]:
1 +∘÷ 1 +∘÷ 1 +∘÷ 1 +∘÷ 1 +∘÷ 1 +∘÷ 1 +∘÷ 1 +∘÷ 1 +∘÷ 1 +∘÷ 1

By using the _fixed point_ `+∘÷⍣=`, we can approximate the value of the golden ratio by computing the expression with as many terms as the machine precision allows.

(Operators-Solutions)=
## Solutions

The following solutions we propose are not necessarily the “best” ones; perhaps you will find other solutions that we have never considered. APL is a very rich language, and due to the general nature of its primitive functions and operators there are always plenty of different ways to express different solutions to a given problem. Which one is “the best” depends on many things, for example the level of experience of the programmer, the importance of system performance, the required behaviour in border cases, the requirement to meet certain programming standards and also personal preferences. This is one of the reasons why APL is so pleasant to teach and to learn!

We advise you to try and solve the exercises before reading the solutions!

```{solution} ex-complex-refunding 
```

We start by defining a numeric vector with the upper limits and a matrix with the refund rates:

In [366]:
limits ← 600 1100 1500 2000
⎕← 4 0⍕ rates ← 3 4⍴100 100 80 50 100 70 30 10 80 60 20 5

The next step is rewriting the traditional refund rate table in the modified version.
For example, for category 1 students, expenses up to 2.000 are refunded in 50%, and then there is a 30% additional refund for expenses up to 1.500.
Why is that?
Because the refund rate for expenses up to 1.500 is 80%, and not 50%, meaning there is a difference of 30%.

By using an _n-wise reduction_, we can subtract each pair of adjacent columns and get these rates:

In [367]:
⎕← modifiedRates ← 2 -/ rates,0

In the expression above, we added a column of zeroes to the right of `rates`.
This can be interpreted as "all expenses above 2.000 have a refund rate of 0%".

Now, we compare each student's expenses with the upper limits of each range:

In [368]:
capped ← expenses ∘.⌊ limits

In [369]:
10↑expenses,' ',capped

Finally, we are ready to multiply each student's capped expenses with the appropriate rates.
We just have to be careful to take into account each student's category to use the appropriate rates:

In [370]:
refunds ← +/capped × modifiedRates[categories;] ÷ 100
⎕← 10↑refunds
⎕← +/refunds

To wrap up, we can put everything into a function:

In [371]:
∇ refunds ← Refund (limits rates categories expenses)
    ;modifiedRates ;capped
    modifiedRates ← 2 -/ rates,0
    capped ← expenses ∘.⌊ limits
    refunds ← +/capped × modifiedRates[categories;] ÷ 100
∇

In [372]:
10↑Refund limits rates categories expenses

In [373]:
+/Refund limits rates categories expenses

```{solution} reductions 
```

In [374]:
⌈/ mat

In [375]:
⌊/ +/ mat

In [376]:
×/ ⌊/[1] mat

In [377]:
×/ ⍴mat

```{solution} scans 
```

In [378]:
-\ 6⍴1

In [379]:
-\ ⌽⍳5

In [380]:
×/ +\ 6⍴1

```{solution} Boolean-scans-and-reductions 
```

In [381]:
∧/ 1 1 1 0 1 1

In [382]:
∧\ 1 1 1 0 1 1

In [383]:
=/ 0 1 1 1 0 1 1

In [384]:
=\ 0 1 1 1 0 1 1

```{solution} reverse-engineer-scan 
```

The result of `×\vec` has six elements, which means the original vector `vec` also has six elements.
The first element of a _scan_ is the first element of the argument vector, thus the first element of `vec` is `7`.
Finally, each subsequent element of the result is going to be the previous element of the result _times_ the respective element of the original vector `vec`.

For example, `14` is `7 × vec[2]`, meaning `vec[2] ← 14 ÷ 7`.
Then, `70` should be `14 × vec[3]`, meaning `vec[3] ← 70 ÷ 14`.
And we can keep going, or we can compute everything with a pairwise reduction:

In [385]:
⎕← vec ← 7, ¯2 ÷/ 7 14 70 210 840

In [386]:
×\ vec  ⍝ verification

```{solution} broken-keyboard-iota 
```

To create a vector with the first `n` integers we can create a vector with `n` elements `1` and then do a _plus scan_ on that:

In [387]:
Iota ← {+\⍵⍴1}

In [388]:
Iota 10

```{solution} triangle-area 
```

We can translate the formula directly to APL and add an _inner product_ for good measure:

In [389]:
Area ← {s ← 0.5×+/⍵ ⋄ (s×s×.-⍵)*0.5}

In [390]:
Area 3 4 5

In [391]:
Area 10 6 8

```{solution} all-different 
```

The _outer product_ is commonly used when you need to try all different combinations of something, so if you have a vector `v`, you can use `v ∘.= v` to compare all items against each other:

In [392]:
v ← ⍳4

In [393]:
v ∘.= v

If a vector only contains unique vectors, then the resulting Boolean matrix will look like the one shown above: a matrix filled with zeroes with a main diagonal composed of ones.

In this context, it suffices to guarantee that each row, or each column, contains a single `1`, which we can do as follows:

In [394]:
1∧.=+/v∘.=v

This way, we found a solution that uses both an _inner product_ and an _outer product_.

```{solution} pairwise-reduction 
```

The _pairwise equals reduction_ will verify which adjacent characters are the same:

In [395]:
2 =/ 'MASSACHUSSETTS'

```{solution} word-in-vector 
```

The first natural step is comparing each character of the left argument to the whole right argument vector:

In [396]:
word ← 'CAN'
sentence ← 'CAN YOU CANCEL MY FLIGHT ON AIR CANADA?'
sentence⍪ word ∘.= sentence

Then, we see an interesting pattern: the left argument word occurs in the positions where the matrix has a diagonal of ones.
So, what we need to do is look for those diagonals of ones in the matrix that is the result of the _outer product_.
This is not very easy to do directly, but we can _rotate_ the rows of the matrix independently to try to align the diagonals:

In [397]:
(¯1+⍳≢word)⌽word ∘.= sentence

Then we can use an _and reduction_ to verify if the diagonals were complete or not:

In [398]:
⍸∧⌿(¯1+⍳≢word)⌽word ∘.= sentence

Putting everything together, we can define our dfn `In`:

In [399]:
In ← {⍸∧⌿(¯1+⍳≢⍺)⌽⍺∘.=⍵}

In [400]:
'CAN' In 'CAN YOU CANCEL MY FLIGHT ON AIR CANADA?'

To solve this exercise with an _inner product_, we can do something different, but similar. But different.

First, we create a matrix with as many rows as the length of the left argument vector, where the sentence in each row has been rotated one character in comparison to the row above:

In [401]:
l ← ≢word
(¯1+⍳l)⌽l(≢sentence)⍴sentence

Next, we use the _inner product_ `∧.=` to look for columns of that matrix that match the word:

In [402]:
⍸word∧.=(¯1+⍳l)⌽l(≢sentence)⍴sentence

```{solution} find-row-in-matrix 
```

One possible way of tackling this problem is by using the _axis_ operator together with _equals_ to compare each row with the vector given:

In [403]:
(4 3⍴'BANCANDANDIG') =[2] 'CAN'

Then, we can use an _and reduction_ to find rows that are filled with `1`:

In [404]:
∧/ (4 3⍴'BANCANDANDIG') =[2] 'CAN'

Finally, we use an _or reduction_ to determine if _any_ of the rows matched:

In [405]:
∨/∧/(4 3⍴'BANCANDANDIG') =[2] 'CAN'

In [406]:
InMat ← {∨/∧/⍺=[2]⍵}

In [407]:
(4 3⍴⍳12) InMat 0 1 2

Another alternative revolves around understanding that the pattern of _and reduction_ after _equals_ can be written as an _inner product_ that will pair the vector with each row of the matrix:

In [408]:
(4 3⍴'BANCANDANDIG')∧.='CAN'

After that, we only need the final _or reduction_ to produce the final Boolean result:

In [409]:
InMat ← {∨/⍺∧.=⍵}

In [410]:
(4 3⍴'BANCANDANDIG') InMat 'CAN'

In [411]:
(4 3⍴⍳12) InMat 0 1 2

```{solution} in-mat-find-better 
```

We can follow the same _inner product_ strategy as in the previous exercise, we just have to make sure we match the dimensions of the left and right arguments of the _inner product_ correctly.
First, notice that we do _have_ to do something:

In [412]:
(3 3⍴9 8 7 4 5 6 3 2 1) InMat 2 3⍴⍳6

LENGTH ERROR
InMat[0] InMat←{∨/⍺∧.=⍵}
                    ∧

When we learned about the _inner product_, we learned that the last dimension of the left argument must match the first dimension of the right argument.
So, in order for this _inner product_ to work, we actually need to transpose the right argument:

In [413]:
(3 3⍴9 8 7 4 5 6 3 2 1) ∧.= ⍉2 3⍴⍳6

By transposing the right argument, we fix this issue.
In a way, when the left and right arguments to an _inner product_ are matrices, it is as if we were combining the rows of the left matrix with the columns of the right matrix.
In the case of the _inner product_ `∧.=`, it is as if we were doing an equality comparison between the rows of the left matrix and the columns of the right matrix.

After transposing the right argument, we need to use _reduce-first_ to determine which rows of the right argument appear in the left argument:

In [414]:
∨⌿ (3 3⍴9 8 7 4 5 6 3 2 1) ∧.= ⍉2 3⍴⍳6

What is also worth noting is that this new implementation will also work when the right argument is just a vector, because the _transpose_ will do nothing in that case, and the final reduction is the same, regardless of it being a _first-axis_ or _last-axis_ reduction:

In [415]:
∨⌿ (4 3⍴'BANCANDANDIG') ∧.=⍉ 'CAN'

Thus, our solution can be:

In [416]:
InMat2 ← {∨⌿⍺∧.=⍉⍵}

```{solution} cross-count 
```

The first step to counting the people in each category is creating two Boolean matrices that encode the category to which each person belongs.
We start by determining which categories exist and then we use an _outer product_ to create said matrices:

In [417]:
∪status

In [418]:
10↑ maritalMat ← status ∘.= ∪status

In [419]:
10↑ graduateMat ← graduated ∘.= ∪graduated

Now, we can use an _inner product_ to _add up_ how many people have a specific marital status _and_ a specific graduation status:

In [420]:
(⍉graduateMat)+.∧maritalMat

We can write this in a dfn and then add the totals row and column, as well as the labels:

In [421]:
]dinput
CrossCount ← {
    binw ← ∪⍵
    bina ← ∪⍺
    mat ← (bina∘.=⍺)+.∧⍵∘.=binw
    mat ,← +/ mat
    mat ⍪← +⌿ mat
    (' ',binw,⊂'Total')⍪(bina,⊂'Total'),mat
}

In [422]:
graduated CrossCount status

```{solution} trim-long-subvectors 
```

To use the operator _at_, we can choose one of two approaches:

 - we compute the lengths of all the nested vectors and find the indices of the long ones; or
 - we use a Boolean function to determine which nested vectors are too long.

In this particular example, both approaches are rather similar.
We can start by defining two small auxiliary functions:

In [423]:
Trim ← {3↑⍵}
IsLong ← {3<≢⍵}
v ← ⍳¨⍳5

Now, we can use `IsLong` to determine the indices of all the nested vectors that are too long:

In [424]:
⎕← longIndices ← ⍸IsLong¨v

Then, we can use the operator _at_ to apply the function `Trim` on those indices.
We just have to remember to use _each_ because, otherwise, the right argument of the function `Trim` would be a vector of all the vectors that are too long:

In [425]:
Trim@longIndices ⊢ v  ⍝ ¨ missing

LENGTH ERROR
      Trim@longIndices⊢v  ⍝ ¨ missing
      ∧

In [426]:
(Trim¨)@longIndices ⊢ v

The alternative approach was to use the function `IsLong` as the Boolean selector, in which case it _also_ needs the operator _each_.
The operator _each_ is also needed in this case because the argument of the right operand of _at_ is the whole array, and not each of its successive elements:

In [427]:
(Trim¨)@IsLong v  ⍝ ¨ missing

RANK ERROR: Right operand and argument ranks differ
      (Trim¨)@IsLong v  ⍝ ¨ missing
             ∧

In [428]:
(Trim¨)@(IsLong¨) v

Thus, our function `TrimLong` could be defined, for example, as:

In [429]:
Trim ← {3↑⍵}
IsLong ← {3<≢⍵}
TrimLong ← {(Trim¨)@(IsLong¨) ⍵}

```{solution} rank 
```

If we want to compute the totals for each _major cell_, one possible solution is to define an auxiliary function that computes totals for a matrix and then we can use the operator _rank_ to apply it to each _major cell_:

In [430]:
TotaliseMat ← {m⍪+⌿m←⍵,+/⍵}
Totalise ← {TotaliseMat⍤¯1⊢⍵}

In [431]:
⎕RL ← 73
prod ← ?5 2 12⍴50
Totalise prod

```{solution} cross-count-key 
```

We can use the operator _key_ to group the status by the graduation value.
That way, we will have all the statuses of people who have graduated separated from the statuses of the people who have not graduated:

In [432]:
⎕RL ← 73
status ← 'SMDWU'[?300⍴5]
⎕RL ← 73
graduated ← 'YN'[?300⍴2]

In [433]:
graduated {⊂(10↑⍵),'...'}⌸ status

In the code above, we show the first ten statuses for each group (graduated versus not graduated) but we do not know which is which.
To get that information, we must make use of the left argument of the operand:

In [434]:
graduated {⍺,⊂(10↑⍵),'...'}⌸ status

Now we know which group of statuses pertains to graduated people and which doesn't.
The next step is grouping the statuses and counting each group:

In [435]:
graduated {⍺,{≢⍵}⌸⍵}⌸ status

This looks like a reasonable answer, although if you inspect the result closely, you will see that the numbers do not match what we computed in the previous version of this exercise:

In [436]:
graduated CrossCount status

What seems to be the issue..?
If you look even more closely, you will see that the problem is that the two rows we just computed with `{⍺,{≢⍵}⌸⍵}⌸` have the wrong order!
As we have seen in {numref}`Operators-Order-of-the-Result`, the order in which _key_ groups things is dependant on the order in which the key values first appear.
If we take a look at each group of statuses, separated by graduation data, we see that they do not have the same order:

In [437]:
graduated {⍺,⊂(10↑⍵),'...'}⌸ status

For example, the first person that graduated is Single but the first person that did not graduate is Married.
To fix this, we can prepend a character vector with the desired order in the inner _key_.
Then, we need to subtract 1 from each count to make up for the fake value we added in the beginning:

In [438]:
graduated {⍺,{¯1+≢⍵}⌸'SMDUW',⍵}⌸ status

To make our solution even more robust, we can also force the order in which the outer _key_ finds the graduated/not graduated categories.
For that, we prepend the two categories in the order we want and then we need to add two fake statuses to make sure both vectors have the same length.
Then, inside the operand, we need to start by dropping the fake status we added previously:

In [439]:
('YN',graduated) {⍺,{¯1+≢⍵}⌸'SMDUW',1↓⍵}⌸ 'xx',status

To conclude this exercise, we just need to add the totals and the labels.

In [440]:
]dinput
CrossCountKey ← {
    statusOrder ← 'SMDWU'
    base ← ('YN',⍺) {{¯1+≢⍵}⌸ statusOrder,1↓⍵}⌸ '  ',⍵
    base ,← +/base
    base ⍪← +⌿base
    (' ',statusOrder,⊂'Total')⍪('YN',⊂'Total'),base
}

In [441]:
graduated CrossCountKey status

```{solution} house-market-sales 
```

The questions that were asked about the matrix `data` boil down to a series of applications of the operator _key_.

The first question asks:

 - What was the most expensive house sold in each city, per year?

To answer this, we can use the operator _key_ with the columns for the year and the location given as the left argument:

In [442]:
⎕RL ← 73
data ← ⍉↑(2015+?103⍴3)(?103⍴4)(('LIS' 'MAD' 'BER')[?103⍴3])(?100+103⍴300)
header ← 'Year' 'Quarter' 'Location' 'Sale'

In [443]:
data[;1 3] {⍺,⌈⌿⍵}⌸ data[;4]

The order of the result is a bit chaotic, but that could be fixed by sorting the result (which you will learn to do in {numref}`Mathematical-Functions-Sorting-and-Searching-Data`).

Another alternative would be adding fake rows to the left argument to force the sorting to be like you want it to be.
This becomes a bit less cumbersome if you apply the operator _key_ twice (once for the year and once for the location) instead of everything at once:

In [444]:
years ← 2015 + ⍳3
mat ← data[;3] {⍺, (years,⍵[;1]) {⌈⌿,⍵[;4]}⌸ 0⍪0⍪0⍪⍵}⌸data
((⊂'Most expensive house'),years)⍪mat

 - How many sales did the real estate company make per year and per quarter?

In [445]:
Qs ← ⍳4
mat ← (years,data[;1]) {⍺,{¯1+≢⍵}⌸ Qs,1↓⍵[;2]}⌸ 0⍪0⍪0⍪data
'Year' 'Q1' 'Q2' 'Q3' 'Q4'⍪mat

 - What was the volume of sales per year in millions of euros?

In [446]:
data[;1] {⍺,(+⌿⍵)÷1000}⌸ data[;4]

 - What about per year and per location?

In [447]:
data[;1] {⍺, ⍵[;1] {⍺,(+⌿⍵)÷1000}⌸ ⍵[;2]}⌸ data[;3 4]

```{solution} minesweeper 
```

We will break the solution to this problem in two smaller problems.
First, we will compute a matrix with clues for all possible squares, counting how many mines are in the neighbouring region.
Then, we replace non-mine squares with the corresponding clues.

First, we use the operator _stencil_ to count the mines:

In [448]:
⎕← mines ← 3 4⍴'⎕*⎕⎕**⎕⎕*⎕⎕*'

In [449]:
⎕← clues ← {+⌿'*'=,⍵}⌺3 3⊢mines

Now, we can use _index of_ to find which indices do not pertain to mines and then we use the operator _at_ to do the replacement:

In [450]:
notMines ← ⍸'*'≠mines
clues[notMines]@notMines⊢mines

We can put both steps together in a small function

In [451]:
]dinput
MakeClues ← {
    clues ← {+⌿'*'=,⍵}⌺3 3⊢⍵
    notMines ← ⍸'*'≠⍵
    clues[notMines]@notMines⊢⍵
}

In [452]:
MakeClues mines

```{solution} stencil-n-wise-reduction 
```

The operator _stencil_ can be used to create the windows of size `n` that we need, and then we can use a regular _reduction_ inside each window.

For example, here is a pairwise sum:

In [453]:
2 +/ ⍳10

And the same thing with the operator _stencil_:

In [454]:
⎕← {⊂⍵}⌺2⊢⍳10
{+/⍵}⌺2⊢⍳10

There are two things we have to pay attention to, though.
The first one has to do with the padding that _stencil_ adds, which we need to get rid of.

Compare this _n-wise multiplication_:

In [455]:
4 ×/ ⍳5

With the similar code that uses _stencil_:

In [456]:
⎕← {⊂⍵}⌺4⊢⍳5
{×/⍵}⌺4⊢⍳5

To fix this issue, we need to compute how much padding is added and we need to _drop_ from the beginning and the end the results that came from windows that had padding.
Recall that in {numref}`Operators-Padding-and-Window-Size` we saw the formula to compute how much padding _stencil_ adds:

In [457]:
ws ← 4
p ← ⌊(ws-1)÷2
⎕← (-p)↓p↓ {⊂⍵}⌺ws⊢⍳5
⎕← (-p)↓p↓ {×/⍵}⌺ws⊢⍳5

The second thing to bear in mind is how this is written in a _user-defined operator_.

We could write a tradop:

In [458]:
∇ result ← n (F _NWiseReduce) vector ;p
    p ← ⌊(n-1)÷2
    (-p)↓p↓{F/⍵}⌺n⊢vector
∇

In [459]:
2 +_NWiseReduce ⍳10

In [460]:
6 ×_NWiseReduce ⍳10

We can also write a drop.
In that case, the left operand to the dop will be used inside a dfn that is the operand of _stencil_.
This apparently correct definition does not work:

In [461]:
_NWiseReduce ← {p ← ⌊(⍺-1)÷2 ⋄ (-p)↓p↓{⍺⍺/⍵}⌺⍺⊢⍵}

The issue lies in the fact that `_NWiseReduce` isn't really a dop because it does not reference neither `⍺⍺` nor `⍵⍵`.
The `{⍺⍺/⍵}` does **not** make `_NWiseReduce` a dop.
Instead, it makes it look like `{⍺⍺/⍵}` is an operator and we trying to pass it as the left operand to _stencil_.
Instead, we need to give a name to the left operand and then use that name inside the operand to _stencil_:

In [462]:
_NWiseReduce ← {F ← ⍺⍺ ⋄ p ← ⌊(⍺-1)÷2 ⋄ (-p)↓p↓{F/⍵}⌺⍺⊢⍵}

```{solution} power-if 
```

The conditional execution of `F` can be achieved with the operator _power_ if we use the Boolean `G right` as the right operand to _power_:

In [463]:
_If_ ← {(⍺⍺⍣(⍵⍵ ⍵)) ⍵}

In [464]:
TimesTen ← {10×⍵}
IsSmall ← {⍵<10}

In [465]:
TimesTen _If_ IsSmall 5

In [466]:
TimesTen _If_ IsSmall 12

To make the derived function of `_If_` ambivalent, we can resort to a clever trick and the conditional assignment to `⍺` inside dfns.
We assign `⍺` to the _right tack_ which is the identity function, and then we just put `⍺` on the left of `⍺⍺` and `⍵⍵`.
If the value of `⍺` was provided (if the derived function is being used dyadically), then that value is passed to the left and right operands, as intended.
If the derived function is being used monadically, then `⍺` is set to the _identity function_, and it won't change anything:

In [467]:
_If_ ← {⍺ ← ⊢ ⋄ ⍺ (⍺⍺⍣(⍺ ⍵⍵ ⍵)) ⍵}

In [468]:
10 +_If_ IsSmall 8

In [469]:
10 +_If_ IsSmall 13