(Operators-Definitions)=
## Definitions

(Operators-Operators--Derived-Functions)=
### Operators & Derived Functions

We have already seen some operators: _reduce_ (described in [this section](Some-Primitive-Functions.ipynb#Reduce)), _axis_ (which you first learned about in [this section](Some-Primitive-Functions.ipynb#Axis)), and _each_ (seen in [this section](Nested-Arrays-Continued.ipynb#Each)).
Let us characterise them precisely:

 - There are built-in (_primitive_) operators and user-defined operators.
 - An _operator_ is similar to a function, but rather than working on arrays to produce a result, which is also an array, an operator works on functions (and sometimes an array) to produce a new function.
 - The new function generated by the operator and its argument(s) is called a _derived function_.
 The _derived function_ can be applied to arrays, in the same way as any other function.
 - The arguments passed to the operator are commonly referred to as _operands_, to distinguish them from the arguments to the derived function.
 - Monadic operators take a single operand on their **left**.
 This is in contrast to monadic _functions_, which take their single argument to the _right_.
 - Dyadyc operators have two operands, one on each side.
 The operands to an operator are usually functions, but it is not uncommon for _user-defined operators_ to take one function and one array operand.
 - The _derived function_, in turn, can be monadic, dyadic, or ambivalent.
 - Neither of the functions supplied as arguments to an operator nor the resultant _derived function_ can be niladic.

For example, in the expression

In [1]:
+/3 5 6

the _reduce_ operator (`/`) operates on the function _plus_ to produce the derived function _plus reduce_.
This derived function is then applied to `3 5 6` to produce a result.

```{admonition} Attention 
:class: attention
You must not be confused by the fact that some symbols are used to represent both a function and an operator.
This is the case for `/` and `\`.
```

In the expression

In [2]:
1 1 0 1 0 / 6 2 9 4 5

the slash (`/`) represents the dyadic _function compress_ because both arguments to the `/` are arrays.

In the expression

In [3]:
+/ 6 2 9 4 5

the same symbol represents _reduce_, which is an _operator_, because the left argument to `/` is a function.

The association of `+` with `/` creates a _derived function_, which could be parenthesised as `(+/)`:

In [4]:
(+/) 6 2 9 4 5

Even though it is not necessary to do so.

For clarification, we can define a synonym for the derived function:

In [5]:
Sum ← +/

Until now, we have only considered it as a _monadic_ derived function:

In [6]:
+/ 6 2 9 4 5

This can be made more evident by using the synonym:

In [7]:
Sum 6 2 9 4 5

But, we shall soon see that it may also be used as a _dyadic_ function:

In [8]:
2 +/ 6 2 9 4 5

Or, using the synonym:

In [9]:
2 Sum 6 2 9 4 5

So, we can say that this _derived function_ is _ambivalent_.

(Operators-Sequences-of-Operators)=
### Sequences of Operators

_Derived functions_ behave exactly like plain primitive functions.
So, they can be the argument of a second (and a third ...) operator:

In [10]:
+/¨ (3 4 6)(4 9 7 1)(3 1)

The left operand of _each_ is the derived function `(+/)`, so we could have written:

In [11]:
(+/)¨ (3 4 6)(4 9 7 1)(3 1)

which may make it clearer that the operator _each_ is operating on the _derived function_ `+/`, and not just on `/`.
Another way of verifying this is by using the synonym `Sum` we defined above:

In [12]:
Sum¨ (3 4 6)(4 9 7 1)(3 1)

Now, suppose that we no longer want to add up vectors, but three small matrices instead:

In [13]:
⎕← a ← 2 3⍴⍳6

In [14]:
⎕← b ← 4 2⍴1 0 0 1 0 1

In [15]:
⎕← c ← 3 5⍴8 3 4 2 0 0 3 5 1 7 3 6 2 1 7

Because they are matrices, we must choose the axis along which we add them up.
Of course, we could use the two operators `/` and `⌿`, but if the arrays had been of a higher rank, an explicit axis specification might have been necessary.
It could also be that we just prefer an explicit axis specification.
If so, a third level of operator* can be added:

```{admonition} Footnote 
:class: note
Although the _axis specification_ shares some properties with operators, it is a special syntactical element and not **really** an operator; cf. {numref}`Operators-Axis` below.
```

In [16]:
+/[2]¨a b c  ⍝ (((+/)[2])¨)a b c

In [17]:
+/[1]¨a b c  ⍝ (((+/)[1])¨)a b c

 - The first operator is `/`, with left operand the function `+`.
 - The second "operator" is `[]`, with left operand the (derived) function `+/` and "right" operand the array `2` (or `1`), specifying the axis.
 - The third operator is `¨`, with left operand the (derived) function `+/[n]`.

(Operators-List-of-Built-in-Operators)=
### List of Built-in Operators

Dyalog APL has a rich set of built-in operators.
You will find a full list with detailed syntax and examples in {numref}`Appendices-Dyalog-APL-Operators`.

(Operators-More-About-Some-Operators-You-Already-Know)=
## More About Some Operators You Already Know

(Operators-Reduce)=
### Reduce

Up to now, we have used _reduce_ with rather basic functions (`+`, `×`, `⌈`, `,`), but it can also be used, less obviously, with functions like _reshape_, _compress_, and _replicate_.
In these cases, the derived function typically takes a 2-item nested vector as its argument, and the effect is to insert the function (the operand to the operator) between the two items of this vector.

Just remember this:

Since `+/ (2 4 3)(7 1 5)` is equivalent to `⊂(2 4 3) + (7 1 5)`, then, `⍴/ (2 4 3)(7 1 5)` is equivalent to `⊂(2 4 3) ⍴ (7 1 5)`.

Here is an example of _reduction by reshape_:

In [18]:
⍴/ (2 5)(3 1 9 4 1 0 7)

This _looks_ very much like `(2 5) ⍴ (3 1 9 4 1 0 7)`, but the result is not a matrix.
It is a scalar containing a _nested_ matrix, for the reason already seen in {numref}`Nested-Arrays-Continued-Reduction`: the reduction of a vector always gives a scalar.

Now, here is a _reduction by compression_:

In [19]:
// (1 1 0 1 0 1 1) 'Strange'

Another _by replication_:

In [20]:
// (1 1 0 4 0 1 2) 'Strange'

And another _by index of_:

In [21]:
⍳/ (2 6 1 7) (2 4⍴3 7 8 4 2 5 6 0)

(Operators-n-Wise-Reduce)=
### $n$-Wise Reduce

(Operators-n-Wise-Reduce-on-Vectors)=
#### $n$-Wise Reduce on Vectors

The derived functions of _reduce_ can be used with two arguments.
This form is called _n-wise reduce_.

When applied to vectors, _n-wise reduce_ has the syntax `r ← scope f/ vector`, where `f` is a dyadic function.

This special kind of _reduce_ splits the vector into (overlapping) slices of length equal to `scope`, and reduces each slice using the specified function.

For example,

In [22]:
2 ×/ 8 10 7 2 6 11

means

In [23]:
(×/8 10) (×/10 7) (×/7 2) (×/2 6) (×/6 11)

i.e.,

In [24]:
(8×10)   (10×7)   (7×2)   (2×6)   (6×11)

Similarly,

In [25]:
3 +/ 8 10 7 2 6 11

means

In [26]:
(+/8 10 7) (+/10 7 2) (+/7 2 6) (+/2 6 11)

i.e.,

In [27]:
(8+10+7)   (10+7+2)   (7+2+6)   (2+6+11)

The size of the result is always `(1+≢vector)-scope`.

We can try this with other functions that give nested results:

In [28]:
2 ,/ 8 10 7 2 6 11

However, we need to be careful to disclose the results when we write out the several explicit reductions:

In [29]:
(⊃,/8 10) (⊃,/10 7) (⊃,/7 2) (⊃,/2 6) (⊃,/6 11)

i.e.,

In [30]:
(8,10)    (10,7)    (7,2)    (2,6)   (6,11)

If we hadn't included the _disclose_ function next to each _reduction_, we would introduce an extra level of depth by mistake:

In [31]:
(,/8 10) (,/10 7) (,/7 2) (,/2 6) (,/6 11)

Another example, using `⍴/`:

In [32]:
2 ⍴/ 2 4 1 3 7

means

In [33]:
(⊃⍴/2 4) (⊃⍴/4 1) (⊃⍴/1 3) (⊃⍴/3 7)

i.e.,

In [34]:
(2⍴4) (4⍴1) (1⍴3) (3⍴7)

The same result would have been obtained using _replicate_:

In [35]:
2 // 2 4 1 3 7

(Operators-n-Wise-Reduce-on-Arbitrary-Arrays)=
#### $n$-Wise Reduce on Arbitrary Arrays

The general syntax is `r ← scope f/[axis] array`, where:

 - `f` stands for any dyadic function;
 - the `array` is split into slices along the specified `axis`; and
 - the left argument `scope` can be positive (as in the examples above), zero, or negative:
   - if `scope` is positive, `reduce` is applied to (overlapping) slices of length equal to `scope`;
   - if `scope` is zero, `r` has the same shape as `array`, except that its length along the axis selected by `axis` is incremented by `1`, and it is filled with the _identity item_ for the function `f`. This is explained in {numref}`Operators-Non-commutative-Functions`;
   - if `scope` is negative, each slice is reversed before `reduce` is applied.

Here are some examples which use this matrix:

In [36]:
⎕← tam ← 3 5⍴2 3 5 8 8 4 6 2 5 9 1 4 9 7 8

 - Obtain the largest items of 2 adjacent columns:

In [37]:
2 ⌈/ tam

 - Add up pairs of adjacent rows:

In [38]:
2 +⌿ tam

 - Return a matrix with one more column, filled with zeroes (identity item of addiction):

In [39]:
0 +/ tam

 - Return a matrix with one more row, filled with ones (identity item of multiplication):

In [40]:
0 ×/[1] tam

 - Obtain the difference between adjacent values (`14-11`, `15-14`, ...):

In [41]:
¯2 -/ 11 14 15 21 23 30 28 34

(Operators-Axis)=
### Axis

Strictly speaking, axis is not an operator.
It has different syntax (consisting of **two** brackets enclosing a numeric value to the right of a function) and applies in different ways depending on the function that it modifies.
However, applying a function "with axis" does apply a transformation and produces a derived function, and it is common to think of axis as an operator.

It is possible to use _axis_ with any of the _scalar dyadic functions_.
This can be useful for example to add the items of a vector to each of the rows of a matrix, or multiply the columns of a matrix by different values:

In [42]:
tam

In [43]:
tam +[1] 8 6 9

In [44]:
tam ×[2] 2 5 0 2 1

The following functions can use the _axis_ operator:

| Function(s) | Valence | Notes |
| :- | :- | :- |
| `+` `×` `⌈` `∧` `≤` etc... | Dyadic | All _scalar dyadic functions_ (see {numref}`Appendices-Scalar-Dyadic-Functions`) |
| `↑` and `↓` | Monadic and dyadic. | n/a |
| `⌽` and `⊖` | Monadic and dyadic. | n/a |
| `,` | Monadic and dyadic | n/a |
| `⍪` | Dyadic | n/a |
| `⊂` | Monadic and dyadic | n/a |
| `⊂` and `⊃` | Monadic | APL2-like split and mix (`⎕ML > 1`, cf. {numref}`Nested-Arrays-Continued-Compatibility-and-Migration-Level`) |
| `/`, `⌿`, `\`, and `⍀` | Dyadic | Beware to avoid confusion between the functions and the operators with the same symbol (see the next section) |

(Operators-Scan)=
## Scan

(Operators-Definition-of-Scan)=
### Definition of Scan

_Scan_ is represented by the symbol `\` or `⍀`.
Its most general syntax is `R ← f\[axis]array`, where `f` stands for any appropriate dyadic function.

To understand how it works, let us apply it to a vector.

The $n$th item of `f\vector` is equal to the _reduction_ of the first $n$ items of `vector`.

More generally, the $n$th item of `f\vector` is equal to `f/n↑vector`.

In [45]:
+\ 3 6 1 8 5

As you can see:

 - the 1st item is equal to `+/3`, giving `3`;
 - the 2nd item is equal to `+/3 6`, giving `9`;
 - the 3rd item is equal to `+/3 6 1`, giving `10`;
 - the 4th item is equal to `+/3 6 1 8`, giving `18`; and
 - the 5th item is equal to `+/3 6 1 8 5`, giving `23`.

Notice how the last item of the result of the scan is the same as the result of the corresponding reduction:

In [46]:
(+/ 3 6 1 8 5) ≡ ⊃⌽ +\ 3 6 1 8 5

The method is, of course, the same for a multiplication:

In [47]:
×\ 3 6 1 8 5

Warning! It would be a mistake to always try to deduce the value of each item in the result from its immediate left neighbour.
While it is possible to do this for commutative functions like addition and multiplication, it is not appropriate for non-commutative functions like subtraction:

In [48]:
-\ 3 6 1 8 5

The result is **not** `3 ¯3 ¯4 ¯12 ¯17` as one might first imagine:

 - the 1st item is equal to `-/3`, giving `3`;
 - the 2nd item is equal to `-/3 6`, giving `¯3`;
 - the 3rd item is equal to `-/3 6 1`, giving `¯2`  (`3-(6-1)`);
 - the 4th item is equal to `-/3 6 1 8`, giving `¯10`; and
 - the 5th item is equal to `-/3 6 1 8 5`, giving `¯5`.

So, be careful when using _scan_ with non-commutative functions.

When applied to matrices or higher rank arrays, _scan_ works along the specified axis.
If the axis specification is omitted, `\` works along the _last_ axis and `⍀` works along the _first_ axis, just like their counterparts `/` and `⌿`.

In [49]:
+\[2] tam

In [50]:
(+\[2]tam) ≡ +\tam

In [51]:
+\[1] tam

In [52]:
(+\[1]tam) ≡ +⍀tam

(Operators-Scan-with-Binary-Values)=
### Scan with Binary Values

_Scan_ is very useful when applied to binary values.

In [53]:
∨\ 0 0 0 0 1 1 0 1 0 0 1 1

Because the function _or_ gives the result 1 as soon as one of its arguments is 1, _or scan_ repeats (or "spreads") the first 1 up to the end of the vector.

If we use the function _and_, we see that _and scan_ reverts the whole vector to zero on the first zero:

In [54]:
∧\ 1 1 1 1 0 1 1 0 0 1 1 0

By using _less than_, we can mark the position of the first 1:

In [55]:
<\ 0 0 0 0 1 1 0 1 0 0 1 1

And by using _less than or equal to_ we mark the position of the first 0:

In [56]:
≤\ 1 1 1 1 0 1 1 0 0 1 1 0

(Operators-Applications-of-Scan)=
### Applications of Scan

_Scan_ can be used to solve common problems in a very simple way:

(Operators-Inflate-Values)=
#### Inflate Values

Someone forecasts investments in a foreign country for the next 5 years:

In [57]:
inv ← 2000 5000 6000 4000 2000

But the country in question suffers from inflation, and the inflation rates are forecasted as follows:

In [58]:
inf ← 2.6 2.9 3.4 3.1 2.7

The cumulative consequence of these inflation rates can be calculated by multiplying them all with a _times scan_:

In [59]:
7 3⍕ ×\ 1+inf÷100

Now, the investments expressed in "future values" would be:

In [60]:
9 2⍕ inv × ×\1+inf÷100

Finally, the year after year cumulative investment may be obtained by a _plus scan_:

In [61]:
9 2⍕ +\ inv × ×\1+inf÷100

As you can see, we employed two _scans_ in the same expression.

(Operators-Remove-LeadingTrailing-Blanks)=
#### Remove Leading/Trailing Blanks

One often has to remove leading (or trailing) blanks from a character vector.
We can use the _or scan_ to do it.
The details of the method are shown here:

In [62]:
lb ← '    Remove my 4 leading blanks.'
lb≠' '

In [63]:
∨\ lb≠' '

In [64]:
(∨\lb≠' ')/lb

This can be coded in a small utility dfn:

In [65]:
CutBlanks ← {(∨\' '≠⍵)/⍵}

This expression is recognised by Dyalog APL as an _idiom_, and processed very quickly.

To remove trailing blanks, it would suffice to reverse the vector, remove leading blanks as above, and then reverse it back again.

(Operators-Outer-Product)=
## Outer Product

(Operators-Definition-of-Outer-Product)=
### Definition of Outer Product

Imagine that you have calculated the multiplication table for the integers 1 to 9; you could present it like this:

$$\begin{array}{|c|rrrrrrrrr|}
\hline
\color{red}\times & 1 & 2 & 3 & 4 & 5 & 6 & \color{red} 7 & 8 & 9 \\
\hline
1 & 1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9 \\
2 & 2 & 4 & 6 & 8 & 10 & 12 & 14 & 16 & 18 \\
\color{red} 3 & 3 & 6 & 9 & 12 & 15 & 18 & \color{red} {21} & 24 & 27 \\
4 & 4 & 8 & 12 & 16 & 20 & 24 & 28 & 32 & 36 \\
\text{etc.} & \text{etc.} & & & & & & & & & & \\
\hline
\end{array}$$

The task of calculating this table consists of taking pairs of items from two vectors (the column and row headings), and combining them with the function at the top left.
For example, `3 × 7` gives `21` (shown above in red).
Once the operation has been repeated for all the possible pairs, one obtains what is called, in APL, the _outer product_.

We can change the values and replace the multiplications by additions:

$$\begin{array}{|c|rrrrrrrrr|}
\hline
\color{red}+ & 8 & 5 & 15 & \color{red} 9 & 11 & 40 \\
\hline
5 & 13 & 10 & 20 & 14 & 16 & 45 \\
\color{red} 4 & 12 & 9 & 19 & \color{red} {13} & 15 & 44 \\
10 & 18 & 15 & 25 & 19 & 22 & 50 \\
3 & 11 & 8 & 18 & 12 & 14 & 43 \\
\hline
\end{array}$$

_Outer product_ is a dyadic operator represented by a dot (`.`).
Its operands are:

 - on its right, the dyadic function involved (multiplication or addition in the examples above);
 - on its left, a small circle named _jot_ (`∘`).
 This character is typed with <kbd>Ctrl</kbd>+<kbd>j</kbd>.
 In this specific case, it acts as a "no-op" (no operation) which just takes the place of the left argument.

So, the two tables above can be written like this:

In [66]:
(⍳9) ∘.× (⍳9)

In [67]:
5 4 10 3 ∘.+ 8 5 15 9 11 40

(Operators-Extensions)=
### Extensions

(Operators-Other-Functions)=
#### Other Functions

The function used in an outer product can be any primitive or user-defined dyadic function, so _outer product_ is an operator of amazing power.

Imagine you have written a little function to calculate the length of the hypotenuse of a right-angled triangle from the lengths of the other 2 sides given as the left and right argument:

In [68]:
Hypo ← {(+/⍺ ⍵*2)*0.5}

In [69]:
3 Hypo 4

You can test it on a number of combinations of lengths in one expression like this:

In [70]:
8 3⍕ 3 6 12 ∘.Hypo 4 1 8 7 5

Now, let's have some fun with relational functions:

In [71]:
(⍳5) ∘.= (⍳5)

In [72]:
(⍳5) ∘.< (⍳5)

In [73]:
(⍳5) ∘.≥ (⍳5)

We shall study some applications of _outer product_ like `∘.<` or `∘.⌊` in {numref}`Operators-Applications-of-Outer-Product`.

Some other _outer products_ like `∘.⍴`, `∘.,`, or `∘./`, produce nested arrays:

In [74]:
3 4 2 ∘.⍴ 6 3 7

In [75]:
3 0 2 ∘./ 5 1 7

In [76]:
3 1 2 ∘., 6 3 0 7

In [77]:
3 2 4 ∘.↑ 5 8 4

(Operators-Other-Shapes-and-Types-of-Data)=
#### Other Shapes and Types of Data

We have, so far, applied _outer product_ to numeric vectors.
Of course, it can also be used with character data and/or higher rank arrays.
When applied to higher rank arrays, the result becomes very big quickly, because each item of the left array has to be combined with each item of the right one.

In an operation like `r ← a ∘.f b`, the shape of `r` is equal to `(⍴a),⍴b`.

In [78]:
⎕← left ← ↑'DIMITRI' 'GUNTHER'

In [79]:
right ← 'VERONICA'
⎕← result ← left ∘.= right

With a bit of APL code, we can show the arguments next to the result, to help you understand how the result has been calculated:

In [80]:
↑(⊂' ',right)⍪¨⊂[2 3]left,result

In and of itself, this code is worth studying a bit, so make sure you understand what is happening before moving on.

(Operators-Applications-of-Outer-Product)=
### Applications of Outer Product

(Operators-Exhaustive-Search)=
#### Exhaustive Search

Because _outer product_ uses a dyadic function to combine **all** items of the left argument with **all** items of the right argument, _outer product_ is often used when some kind of exhaustive computation needs to be done.
One such example is that of exhaustive search.

As an example, suppose you want to figure out if there is a way to add one number from the vector `5 1 16 42 63 7 10` to another number from the vector `24 45 18 31 29 43 67` to get `73`.

With _outer product_, this is quite an easy question to answer:

In [81]:
5 1 16 42 63 7 10∘.+24 45 18 31 29 43 67

In [82]:
73∊5 1 16 42 63 7 10∘.+24 45 18 31 29 43 67

If you flip the arguments to _membership_ and use _where_, you can find the position(s) where `73` is:

In [83]:
⍸(5 1 16 42 63 7 10∘.+24 45 18 31 29 43 67)∊73

This pattern of exhaustive computations is fairly common, and although it generally is not the most computationally efficient way of solving a problem, it is generally fast enough to prototype as a first approach.

(Operators-Draw-a-Bar-Chart)=
#### Draw a Bar Chart

Imagine that you have to represent a list of values with a bar chart.
Perhaps you will use dedicated graphical software, and you'd be right, but just have a look at this elegant solution, which again uses an _outer product_.

Here is the list of values that we want to chart:

In [84]:
nums ← 1 3 0 7 9 8 5 4 2 3 1

Let us first calculate the vertical scale.
It is made of the integers from 9 to 1 in reverse order and can be obtained by:

In [85]:
⌽⍳⌈/nums

Then, let us compare this scale to the values; an _outer product_ will build columns of 1s up to the correct height:

In [86]:
(⌽⍳⌈/nums) ∘.≤ nums

And to draw the graph, we can index a 2-character vector, exactly as we did in {numref}`Data-and-Variables-The-Shape-of-the-Result`:

In [87]:
' ⎕'[1+(⌽⍳⌈/nums)∘.≤nums]

(Operators-Decreasing-Refunding)=
#### Decreasing Refunding

Some students have spent money to buy expensive books for their studies:

In [88]:
exp ← 740 310 1240 620 800 460 1060

Their university agrees to refund them, but places the following limits on refunding rates:

 - for expenses from 0 to 500, the rate is 80%;
 - for expenses from 500 to 900, the rate is 50%; and
 - for higher expenses, nothing is paid.

We could say exactly the same thing in a somewhat different way:

 - for expenses from 0 to 900, we get 50%; and
 - starting again from **0** to 500, we get an **additional** 30%.

Even if this rule may seem strange, both methods give the same result.
For example, a student who spent 740€ would get:

 - with the "traditional" rule, 80% of 500 plus 50% of 240:

In [89]:
(0.8×500)+0.5×240

 - with our "foolish" rule, 50% of 740 plus 30% of 500:

In [90]:
(0.5×740)+0.3×500

Now, let us limit the expenses to the given maxima:

In [91]:
exp ∘.⌊ 900 500

The first column contains the expenses limited to 900, and the second contains the expenses limited to 500.

According to our rewritten rules, we must pay 50% of the first column plus 30% of the second.
For that, we can multiply the columns by `0.5 0.3` (using _axis_) and add them:

In [92]:
+/ (exp∘.⌊900 500) ×[2] 0.5 0.3

And the total refund is, of course:

In [93]:
+/ +/ (exp∘.⌊900 500) ×[2] 0.5 0.3

If we laminate the original vector, we can see the expenses and the refunding:

In [94]:
exp,[0.5] +/(exp∘.⌊900 500)×[2]0.5 0.3

(fig-Outer_Product)=
```{figure} res/Outer_Product.png
---
name: Outer_Product
---
Outer product.
```

(Operators-Exercise-on-Outer-Product)=
### Exercise on Outer Product

**Exercise 1**:

Let us try to generalise the method used here above.

In our example, we had chosen a very simple case, because we had only two slices, and all the students used the same scale.
Let us now imagine a slightly more complex case:

 - the students are classified in three categories, which have different refunding rates; and
 - we now have four different expense ranges.

The new conditions are expressed with the traditional notation, in a table:

| Category \ Range | 0 to 600 | 600 to 1.100 | 1.100 to 1.500 | 1.500 to 2.000 |
| :- | :-: | :-: | :-: | :-: |
| Category 1 | 100% | 100% | 80% | 50% |
| Category 2 | 100% | 70% | 30% | 10% |
| Category 3 | 80% | 60% | 20% | 5% |

Try to write a function `Refund` to solve this problem.
Using loops is strictly prohibited, and could be punished with high severity!

You can test your solution with these variables:

 - The table of rates, topped by the expense limits:

In [95]:
⎕← studRates ← 4 4⍴600 1100 1500 2000 100 100 80 50 100 70 30 10 80 60 20 5

 - Vector of student expenses:

In [96]:
studExp ← 1500 2300 1030 460 380 340 1150 3000
studExp ,← 1700 1900 440 1050 2380 1980 1600 1000 1270

 - Vector of the category of each student.

In [97]:
studCat ← 1 3 2 3 3 2 2 2 1 1 1 1 1 3 2 3 3

To help you check your solution, here are the results you should obtain:

In [127]:
Refund ← {}
studRates Refund studExp studCat
⍝ 1420 885 901 368 304 340 965 1120 1520 1620 440 1050 1670 884 1080 720 814

(Operators-Inner-Product)=
## Inner Product

_Inner product_ is a generalisation of what mathematicians call _matrix product_, a tool considered by most students as extremely abstract, full of bizarre notations, like $\sum a_{ij}b_{jk}$, and obviously far removed from everyday problems.
You will discover that:

 - the concept is really simple, nearly obvious; and
 - it can be applied to many real life problems.

A simple example will help us.

(Operators-A-Concrete-Situation)=
### A Concrete Situation

A company intends to open a series of hotels and resorts in four countries.
This requires serious investments over a period of five years.
The following table shows these investments (in millions of dollars, of course!):

| Country vs Year | Year 1 | Year 2 | Year 3 | Year 4 | Year 5|
| :- | -: | -: | -: | -: | -: |
| Greece | 120 | 100 | 40 | 20 | 0 |
| Brazil | 200 | 150 | 100 | 120 | 200 |
| Egypt | 50 | 120 | 220 | 350 | 600 |
| Argentina | 0 | 80 | 100 | 110 | 120 |

These figures are contained in a matrix called `invest`:

In [130]:
invest ← 120 100 40 20 0 200 150 100 120 200 50 120
⎕← invest ← 4 5⍴invest,220 350 600 0 80 100 110 120

These investments will be supported by the company itself plus two banks, each taking a certain percentage of the total, depending on the evaluation of each project.
The following table shows how the risks are shared:

| Stakeholder vs Country | Greece | Brazil | Egypt | Argentina |
| :- | -: | -: | -: | -: |
| Bank 1 | 50 | 10 | 20 | 30 |
| Bank 2 | 20 | 60 | 40 | 30 |
| Company | 30 | 30 | 40 | 40 |

Those percentages are contained in a matrix named `percent`:

In [131]:
⎕← percent ← 3 4⍴50 10 20 30 20 60 40 30 30 30 40 40

We would like to calculate, year by year, how much each of the 3 partners is engaged in this project.
For example, let us try to evaluate the contribution of Bank 2 during Year 3:

| Country | Project valuation | Stake | Total invested |
| :- | -: | -: | -: |
| Greece | 40 | 20% | 8 |
| Brazil | 100 | 60% | 60 |
| Egypt | 220 | 40% | 88 |
| Argentina | 100 | 30% | 30 |

The total invested is, thus, 186.

This could have been obtained by the sum of four products:

In [132]:
+/ percent[2;] × invest[;3]÷100

In order to calculate the total invested for each partner and each year, we should repeat that algorithm for all the rows of `percent`, and all the columns of `invest`: this is precisely what an _inner product_ does.

And because it _adds_ a series of _products_, it will be expresseed by a dot (the operator) between a plus and a multiply sign, like this:

In [133]:
percent +.× invest÷100

In {numref}`fig-Inner_Product_Diagram`, we have detailed the elementary products which lead to the calculation for bank 2 in year 3:

(fig-Inner_Product_Diagram)=
```{figure} res/Inner_Product_Diagram.png
---
name: Inner_Product_Diagram
---
Diagram representing the _inner product_ operation.
```

{numref}`fig-Inner_Product_Diagram` has a great advantage: it clearly shows the relations that exist between the 3 matrices:

 - the left argument has as many columns as the right one has rows; and
 - the result has as many rows as the left argument and as many columns as the right one.

As you can see, the item `result[x;y]` is calculated from row `x` of the left argument (`⍺[x;]` in dfn notation) and column `y` of the right argument (`⍵[;y]` in dfn notation).

These rules will be generalised in the next section.

(Operators-Definition-of-Inner-Product)=
### Definition of Inner Product

The syntax of _inner product_ is `r ← x f.g y`, where the _inner product_ is represented by a dot (`.`) and `f` and `g` represent two appropriate dyadic functions (either primitive or user-defined).

The arguments may be arrays of any rank: scalars, vectors, matrices, or higher-rank arrays.
The shape of the arguments and the shape of the result follow very simple rules:

 - the length of the last dimension of the left argument must be equal to the length of the first dimension of the right argument (in other words, `(¯1↑⍴x)≡1↑⍴y`); and
 - the shape of the result is the catenation of the argugments' shapes, in which the common dimension has disappeared (in other words, `(⍴r)≡(¯1↓⍴x),1↓⍴y`).

Of course, as usual, scalars are repeated to fit the appropriate size.

Let us represent scalars by `s`, vectors by `v`, matrices by `m`, and higher-rank arrays by `a`.
The table below shows the same of the result of some _inner products_:

| `r ← x f.g y` | `⍴x` | `⍴y` | `⍴r` |
| :- | -: | -: | -: |
| `a ← a f.g a` | `2 3 8` | `8 5 4` | `2 3 5 4` |
| `a ← a f.g a` | `2 3 8` | `8 3 2` | `2 3 3 2` |
| `m ← m f.g m` | `3 5` | `5 8` | `3 8` |
| `v ← m f.g v` | `4 7` | `7` | `4` |
| `v ← v f.g m` | `4` | `4 7` | `7` |
| `s ← v f.g v` | `10` | `10` | `⍬` |

(Operators-Typical-Uses-of-Inner-Products)=
### Typical Uses of Inner Products

(Operators-Two-Simple-Problems)=
#### Two Simple Problems

Many students imagine that matrix products are complex things, reserved for mathematicians, and far removed from everyday life.
This opinion should be reconsidered: very simple problems can be solved using inner product.

`hms` is a variable which contains a time interval in hours, minutes, and seconds:

In [135]:
hms ← 3 44 29

We would like to convert it into seconds.
We shall see three methods just now, and a fourth method will be given in another chapter.

A horrible solution:

In [136]:
(3600×hms[1]) + (60×hms[2]) + hms[3]

A good APL solution:

In [137]:
+/ 3600 60 1 × hms

An excellent solution with inner product:

In [138]:
3600 60 1 +.× hms

The second and third solutions are equivalent in terms of number of characters typed and similar in performance.
However, **it is recommended** that you use the third one: it will help you become familiar with _inner product_ so that after a certain period, it will become part of your toolkit as an APL programmer.

Here is a very similar example.
Two vectors represent the prices of a certain number of goods and the quantities we bought:

In [140]:
price ← 6 4.2 1.5 8.9 31 18
qty   ← 2 6   3   5   1  0.5

To calculate how much we paid, we can use the beginner's solution, or a solution with a simple _inner product_; they give the same result, of course:

In [141]:
+/ price × qty

In [142]:
price +.× qty

Just to show how it works, {numref}`fig-Inner_Product_Diagram_2` contains an explanatory diagram similar to the one we used for our Banks/Investments example.

(fig-Inner_Product_Diagram_2)=
```{figure} res/Inner_Product_Diagram_2.png
---
name: Inner_Product_Diagram_2
---
Diagram explaining the behaviour of an _inner product_ between two vectors
```

(Operators-A-Useful-Family)=
#### A Useful Family

Used with comparison functions, _inner product_ offers 18 extremely useful derived functions.

Here is a vector `ages` containing the ages of 400 persons:

In [143]:
⎕RL ← 73
⎕← 20↑ages ← ?400⍴100  ⍝ We display the first 20 ages only.

In the same way as we did in {numref}`Some-Primitive-Functions-Reduction-of-Binary-Data`, we can answer some elementary questions:

Are all these people younger than 65?

In [144]:
∧/ ages < 65

Is there at least one person younger than 20?

In [145]:
∨/ ages < 20

How many people are younger than 20?

In [146]:
+/ ages < 20

We can now replace _reduce_ in the previous examples by _inner product_, like this:

Are all these people younger than 65?

In [147]:
ages ∧.< 65

Is there at least one person younger than 20?

In [148]:
ages ∨.< 20

How many people are younger than 20?

In [149]:
ages +.< 20

Clever, isn't it?

These expressions can be read as:

 - `∧.<` means "all smaller" – are the ages **all smaller** than 65?
 - `∨.<` means "at least one is smaller" – is there **at least** one age **smaller** than 20?
 - `+.<` means "how many are smaller" – **how many** ages are **smaller** than 20?

In those three expressions, we have combined `∧`, `∨`, and `+` with `<`.
We could just as well combine them with all the comparison symbols, giving 18 different _inner products_, as shown in this table:

In [151]:
'∧∨+' ∘.{⍺,'.',⍵} '<≤=≥>≠'

(Operators-A-Special-Case-of-a-Comparison-Inner-Product)=
#### A Special Case of a Comparison Inner Product

In this family of _inner products_, `∧.=` is particularly interesting, because it answers the question "are all those values equal?".
For example, applied to vectors of the same length:

In [152]:
'customer' ∧.= 'customer'

In [153]:
'customer' ∧.= 'cucumber'

Let us use this property to search for a word in a matrix of words:

In [155]:
⎕← words ← 8 7⍴'CONTACTCOLUMNSFORTUNEPRODUCTCOLONELPROVIDEMACHINETYPICAL'

If we combine this 8 by 7 matrix with a 7-item vector, compatibility rules are obeyed, and the result will be a 8-item vector:

In [158]:
words ∧.= 'PRODUCT'

The shape of `words` is `8 7` and the shape of `'PRODUCT'` is `7`, so the common dimension disappears, and the result has shape `8`.

Now, let us search for three words:

In [159]:
⎕← three ← 3 7⍴'MACHINECOMFORTPRODUCT'

In [160]:
words ∧.= ⍉three

We must transpose the matrix to be compliant with the compatibility rules, and the result shows what word was found in what row of `words`.

If we wanted to know which words were found, we could add an _or-reduction_:

In [163]:
∨⌿ words∧.=⍉three

If we wanted to know which of the rows in `words` contain words in `three`, we could have used another _or-reduction_, but along the other axis:

In [164]:
∨/ words∧.=⍉three

It may also be useful to search for the positions of said matches, but we can use _index of_ for that:

In [165]:
words ⍳ three

The converse to the expression `∧.=` is `∨.≠`.
(That means that `∧.=` and `∨.≠` always return opposite Boolean values.)
It looks for _different_ values instead of looking for _equal_ values.
Let us look at one simple example:

In [166]:
words ∨.≠ ⍉three

A `1` means that this word in `three` does not match the word in this row of `words`.
So, if a row contains all `1`s, the word in that row does not match any of the words in `three`.
Using _and-reduce_ along the second axis pinpoints the rows of `words` for which this is true:

In [168]:
∧/ words∨.≠⍉three

With a compression, we can see the words that are not found in `three`:

In [169]:
(∧/words∨.≠⍉three) ⌿ words